var AufHeaderAds=(function(){AufHeaderAds=function(obj){this.conf=obj;};AufHeaderAds.prototype={init:function(o){this.navDropdownInit();},log:function(s){if(typeof(console)!=='undefined'&&console.log){console.log(s);}},display:function(){PubSub.publish('mainNav.addItem',{conf:this.conf});},navDropdownSectionsCalled:[],navDropdownSectionsDone:[],navDropdownInit:function(){PubSub.publish('mainNav.itemHoverInit',{});},navDropdownCallback:function(o){PubSub.publish('mainNav.itemHoverCallback',o);}};return AufHeaderAds;})();if(typeof AufHeaderAds!=='undefined'){var appHeaderAds=new AufHeaderAds();}
var sas=sas||{};sas.cmd=sas.cmd||[];var afAd={async:false,adblocked:false,smartLoaded:false,firstInitDone:false,exclusions:[[300,[12,117,118]]],exclusionsAjax:[],multipleformats:{f4040:3,f3206:4,f8120:4,f3243:8,f14140:4,f21150:6,f27316:10},grouphiding:[],scriptObjs:{},disabledFormats:{},renderedFormats:[],deferredFormats:[],instances:{},setup:function(o){sas.cmd.push(function(){sas.setup({networkid:(o&&o.networkId?o.networkId:sas_networkId),domain:(o&&o.domain?(o.domain.indexOf('//')<0?'//'+o.domain:o.domain):sas_domain),async:true,renderMode:sas.renderMode.ON_DEMAND});});afAd.initLogger();},initLogger:function(){if(!window.AdsLogger)return;afAd.logger=new AdsLogger(afLogger);if(window.PubSub){PubSub.subscribe('ad.prerender',function(msg,data){afAd.logEvent('render',data);});}},onecall:function(o){afAd.logEvent('onecall');var formatIds=(o&&o.formatIds?o.formatIds:sas_formatIds);afAd.askedFormats=formatIds.split(',');afAd.initKeywords();sas.cmd.push(function(){sas.call('onecall',{siteId:(o&&o.siteId?o.siteId:sas_siteId),pageId:(o&&o.pageId?o.pageId:sas_pageId),formatId:formatIds,target:(o&&o.target?o.target:sas_target)},{async:true,beforeRender:function(format){afAd.init(sas_manager);afAd.publishEvent('ad.render',format);if(window.PubSub){PubSub.publish('ad.render',format);}},onLoad:function(format){afAd.publishEvent('ad.load',format);if(window.PubSub){PubSub.publish('ad.load',format);}}});});},initKeywords:function(){var utm=window.af_utm;if(!utm&&window.af_getUtm)utm=window.af_getUtm();if(utm&&utm.campaign){afAd.addKeyword('utm_source='+af_utm.source);afAd.addKeyword('utm_medium='+af_utm.medium);afAd.addKeyword('utm_campaign='+af_utm.campaign);}},load:function(o){if(afAd.smartLoaded)return;if(window.aufbidjs){sas_target+=';'+aufbidjs.getQueryStringForAdserver();aufbidjs.debugTarget(sas_target);}
var s=document.createElement('script');s.type='text/javascript';s.async=true;s.src=sas_domain+'/config.js?nwid='+sas_networkId;s.onload=s.onerror=function(){afAd.smartLoaded=true;afAd.recall();};var f=document.getElementsByTagName('script')[0];f.parentNode.insertBefore(s,f);},call:function(domain,siteid,pageid,fids,target){afAd.domain=domain;afAd.siteid=siteid;afAd.pageid=pageid;afAd.askedFormats=fids.split(',');if(afAd.async){sas.cmd.push(function(){sas.setup({networkid:1,domain:(domain.indexOf('//')<0?'//'+domain:domain),async:true,renderMode:sas.renderMode.ON_DEMAND});});sas.cmd.push(function(){sas.call('onecall',{siteId:siteid,pageId:pageid,formatId:fids,target:sas_target},{async:true,beforeRender:function(format){afAd.init(sas_manager);afAd.publishEvent('ad.render',format);if(window.PubSub){PubSub.publish('ad.render',format);}},onLoad:function(format){afAd.publishEvent('ad.onload',format);afAd.publishEvent('ad.load',format);if(window.PubSub){PubSub.publish('ad.load',format);}}});});}else{document.write('<scr'+'ipt type="text/javascript" src="//'+domain+'/call2/pubjall/'+siteid+'/'+pageid+'/'+fids+'/'+Math.round(Math.random()*10000000000)+'/'+sas_target+'?"></scr'+'ipt>');}},init:function(sasmgr){if(!sasmgr||sasmgr&&sasmgr.afad_init)return;if(afAd.firstInitDone){for(var k=0;k<afAd.exclusionsAjax.length;k++){afAd.disable(afAd.exclusionsAjax[k],'async');}}
afAd.scriptObjs={};var r1=/^\<(script|iframe)(\s.*?)\>(.*)$/i,r2=/\s([a-z]+)=(?:"([^"]*)"|([a-z0-9_]+))/gi;var nbs=0;for(var ffid in sasmgr.formats){var scriptUrlFn=null;if(typeof sasmgr.formats[ffid].scriptURL!='undefined'){scriptUrlFn=sasmgr.formats[ffid].scriptURL;}else{scriptUrlFn=function(){return'<scr'+'ipt type="text/javascr'+'ipt" src="'+sasmgr.formats[ffid].scriptSrc()+'"></scr'+'ipt>'};}
var _s=scriptUrlFn();t=r1.exec(_s);var o={_script:_s,type:t[1].toLowerCase(),attrs:{},trail:t[3]};eval(t[2].replace(r2,'o.attrs.$1="$2$3";'));afAd.scriptObjs[ffid]=o;nbs++;}
afAd.scriptObjs.length=nbs;for(var ffid in sasmgr.formats){if(afAd.matchExclu(ffid)){afAd.matchExclu(ffid,true);break;}}
for(var k=0,a=afAd.exclusions;k<a.length;k++){if(afAd.exists(a[k][0])){for(var fids=a[k][1],i=0;i<fids.length;i++){afAd.disable(fids[i],'ex',a[k][0]);}}}
var cssToHide=[];for(var i=0,fids=afAd.askedFormats;i<fids.length;i++){var fid=fids[i];if(!afAd.exists(fid)){cssToHide.push('.sas_FormatID_'+fid);}
for(var j=2,n=afAd.multipleformats['f'+fid]||0;j<=n;j++){if(!afAd.exists(fid+'_'+j)){cssToHide.push('.sas_FormatID_'+fid+'_'+j);}}}
for(var k=0,a=afAd.grouphiding;k<a.length;k++){var h=true;for(var fids=a[k][0],i=0;i<fids.length;i++){h&=!afAd.exists(fids[i]);}
if(h){cssToHide.push(a[k][1]);}}
if(!afAd.async){if(cssToHide.length>0){document.write('<style type="text/css">'+cssToHide.join(',')+' { display:none; }</style>');}}else{if(cssToHide.length>0){afAd.setCss(cssToHide.join(',')+' { display:none; }');}
afAd.clean();}
sasmgr.afad_init=true;afAd.firstInitDone=true;},matchExclu:function(fid,apply){if(typeof(fid)=='string')fid=parseInt(fid.replace(/f/i,''));if(!afAd.exists(fid))return false;for(var k=0,a=afAd.exclusions;k<a.length;k++){if(fid==a[k][0]){for(var fids=a[k][1],i=0;i<fids.length;i++){if(afAd.exists(fids[i])){if(apply){afAd.disable(fids[i],'pr',fid);}else{return true;}}}}}
for(var k=0,a=afAd.exclusions;k<a.length;k++){if(afAd.exists(a[k][0])){for(var fids=a[k][1],i=0;i<fids.length;i++){if(fid==fids[i]){if(apply){afAd.disable(a[k][0],'pr',fid);}else{return true;}}}}}
return false;},setCss:function(style){var css=document.getElementById('afAdExclusions');if(!css){css=document.createElement('style');css.type='text/css';css.id='afAdExclusions';document.body.appendChild(css);}
if(css.styleSheet){css.styleSheet.cssText=style;}else{css.innerHTML=style;}},addFormat:function(fid){if(typeof afAd.instances[fid]==='undefined'){afAd.instances[fid]=1;}else{afAd.instances[fid]++;}
return afAd.instances[fid];},render:function(fid,deferred){if(window.sas&&afAd.async){if(fid){sas.cmd.push(function(){sas.render(fid);});afAd.renderedFormats.push(fid);}else{sas.cmd.push(function(){sas.render();if(window.PubSub){PubSub.publish('ad.renderAll');}});}}else if(!afAd.disabledFormats[fid]){if(window.sas&&sas.render&&!deferred){sas.render(fid);}else if(afAd.exists(fid)){var s=afAd.getScript(fid);document.write(s);}}},renderPlaceholder:function(fid){if(afAd.exists(fid)){var a=afAd.scriptObjs['f'+fid].attrs;var s=(a.width?'width:'+a.width+'px;':'')+
(a.height?'height:'+a.height+'px;':'');document.write('<div id="SaS_placeholder_'+fid+'"'+(s?' style="'+s+'"':'')+'></div>');}},renderDeferred:function(fid){afAd.utils.patchDocumentWrite(true);if(afAd.exists(fid)){afAd.render(fid,true);afAd.deferredFormats.push(fid);}},placeAllDeferred:function(){var ifrUnpatchList=[];for(var k=0,fids=afAd.deferredFormats;k<fids.length;k++){var fid=fids[k],r=document.getElementById('SaS_render_'+fid),p=document.getElementById('SaS_placeholder_'+fid);if(r&&p){for(var i=0,a=afAd.utils.getByTagName(r,'script');i<a.length;i++)
afAd.utils.remove(a[i]);ifrUnpatchList=ifrUnpatchList.concat(afAd.utils.getByTagName(r,'iframe'));p.parentNode.insertBefore(r,p);afAd.utils.remove(p);}}
for(var i=0;i<ifrUnpatchList.length;i++){var o=ifrUnpatchList[i],s=(o['afadsrc']||o.getAttribute('afadsrc'));if(s)o.src=s;}
afAd.utils.remove(document.getElementById('SaS_deferBox'));afAd.utils.patchDocumentWrite(false);},exists:function(fid){return(afAd.scriptObjs&&afAd.scriptObjs['f'+fid]);},getScriptURL:function(fid){var s='';if(afAd.exists(fid)){var o=afAd.scriptObjs['f'+fid],a=o.attrs;if(!o.done){s=a.src;o.done=true;}}
return s;},getScript:function(fid){var o=afAd.scriptObjs['f'+fid],a=o.attrs,s='';if(!o.done){if(o.type=='script'&&!a.charset)
a.charset='iso-8859-1';if(o.type=='iframe'){var iid=/\/diff\/1\/(\d+)\//gi.exec(a.src);if(iid)a.id='SaS_InsertionID_'+iid[1];}
s='<'+o.type;for(var i in a)s+=' '+i+'="'+a[i]+'"';s+='>'+o.trail;o.done=true;}
return s;},disable:function(fid,m,exclufid){afAd.disabledFormats[fid]=m;var newfid='f'+fid+'-disabled-'+m+(exclufid?'-('+exclufid+')':'');afAd.scriptObjs[newfid]=afAd.scriptObjs['f'+fid];delete afAd.scriptObjs['f'+fid];if(afAd.async&&sas_manager.exists(fid)){sas_manager.formats[newfid]=sas_manager.formats['f'+fid];delete sas_manager.formats['f'+fid];}},addKeyword:function(keyword){if(sas_target.indexOf(keyword)>=0)return;sas_target+=';'+keyword;afAd.cleanKeywords(sas_target);return sas_target;},cleanKeywords:function(target){return target.replace('/;+/',';');},refresh:function(fids,target){if(!window.sas)return;afAd.async=true;sas.cmd.push(function(){sas_unrenderedFormats=fids.split(',');for(var i=0,l=sas_unrenderedFormats.length;i<l;i++){sas.clean(sas_unrenderedFormats[i]);}});sas.cmd.push(function(){sas.call('onecall',{siteId:sas_siteId,pageId:sas_pageId,formatId:fids,target:(target?target:sas_target)},{async:true,forceMasterFlag:true,resetTimestamp:true,beforeRender:function(format){afAd.init(sas_manager);afAd.publishEvent('ad.render',format);},onLoad:function(format){afAd.publishEvent('ad.onload',format);}});});},clean:function(fids){if(fids){if(window.sas&&sas.clean){var fid,container,formats=fids.split(',');for(var i=0,l=formats.length;i<l;i++){fid=formats[i];sas.clean(fid);if(fid=='300'||fid=='117'){afAd.publishEvent('ad.clean.skin');}
var container=document.getElementById('SaS_render_'+fid);if(container)container.innerHTML='';}}}else{if(window.sas&&sas.clean){sas.clean();}
afAd.publishEvent('ad.clean');afAd.publishEvent('ad.clean.skin');afAd.publishEvent('ad.clean.navitem');}},reset:function(){sas={};sas.cmd=[];afAd.async=true;sas.cmd.push(function(){afAd.call(sas_domain,sas_siteId,sas_pageId,sas_formatIds,sas_target);});for(var i=0,l=afAd.renderedFormats.length;i<l;i++){if(afAd.renderedFormats[i]!=6965){afAd.rerender(afAd.renderedFormats[i]);}}
afAd.render();},recall:function(){if(!afAd.smartLoaded||!afAd.adblocked)return;afAd.reset();window._sp_.loadProxiedSmart();},rerender:function(fid){var e=document.getElementById('sas_'+fid);if(!e)return;if(window._sp_&&window._sp_.protectElement){afAd.subscribeEvent('ad.load',function(format){var e=document.getElementById('sas_'+format);if(e){window._sp_.protectElement(e);}});}
if(window.asmi){var pageid=sas_siteId+'/('+sas_pageName+')';SmartAdServerAjax(sas_pageid,fid,sas_target);}else{sas.cmd.push(function(){afAd.render(fid);});}},detectUTM:function(){if(document.referrer.indexOf(document.domain)==-1){af_setCookie('af_utm2','',-1);if(location.hash){var hash=location.hash.substring(1);if(hash){hash=hash.replace(/&|#/g,'|');splitHash=hash.split('|');var i=0;var utmStr='';for(i=0;i<splitHash.length;i++){switch(splitHash[i].substring(0,10)){case'utm_source':utmStr+=splitHash[i]+'|';break;case'utm_medium':utmStr+=splitHash[i]+'|';break;case'utm_campai':utmStr+=splitHash[i]+'|';break;}}
if(utmStr){af_setCookie('af_utm2',utmStr.slice(0,-1));}}}}
var cookie=af_getCookie('af_utm2');if(cookie){sas_target+=';'+cookie.replace(/\|/g,';');}},logEvent:function(event,data){if(!afAd.logger)return;afAd.logger.logEvent(event,data);},utils:{remove:function(o){if(o)o.parentNode.removeChild(o);},getByTagName:function(r,t){var o=[];for(var i=0,a=r.getElementsByTagName(t);i<a.length;i++)
o.push(a[i]);return o;},addListener:function(elt,event,listener,capture){if(elt&&elt.addEventListener){elt.addEventListener(event,listener,capture);return true;}else if(elt&&elt.attachEvent){return elt.attachEvent('on'+event,listener);}else{var oldListener=elt['on'+event];elt['on'+event]=function(e){if(oldListener){oldListener(e);}
return listener(e);};return oldListener;}},patchDocumentWrite:function(active){var pdw=afAd.utils.patchDocumentWrite;if(active==pdw.active)return;if(!pdw.oDW){pdw.oDW=document.write;pdw.oDWln=document.writeln;var ifrPatch=function(s){return s.replace(/(<iframe[^>]*?)\ssrc=/i,'$1 afadsrc=');};pdw.pDW=(pdw.oDW.call?function(s){pdw.oDW.call(document,ifrPatch(s));}:function(s){pdw.oDW(ifrPatch(s))});pdw.pDWln=(pdw.oDWln.call?function(s){pdw.oDWln.call(document,ifrPatch(s));}:function(s){pdw.oDWln(ifrPatch(s))});}
if(active){document.write=pdw.pDW;document.writeln=pdw.pDWln;}else{document.write=pdw.oDW;document.writeln=pdw.oDWln;}
pdw.active=active;},debug:function(html){var d='';for(var ffid in afAd.scriptObjs)
if((o=afAd.scriptObjs[ffid])&&afAd.scriptObjs[ffid]._script)
d+='- <b>'+ffid+'</b> : '+(html?o._script.replace(/\>/g,'&gt;').replace(/\</g,'&lt;').replace(/src="(.*?target=)(.*?)"/i,'src="<u style="cursor:pointer;" onclick="window.open(\'$1$2\');">$1...</u>"')+'<br>':o._script+'\n');return d;}},topAdsHeight:function(containers){containers=(containers||['SaS_render_117','SaS_render_4856','SaS_render_6917','SaS_render_17821','af_background_relDiv']);var height=0;for(var i=0;i<containers.length;i++){var e=document.getElementById(containers[i]);if(e)height+=e.offsetHeight;}
return height;},eventCallbacks:{},subscribeEvent:function(eventName,callback,keepEvent){var ke=keepEvent||false;if(!this.eventCallbacks[eventName])this.eventCallbacks[eventName]=[];this.eventCallbacks[eventName].push({callback:callback,keepEvent:ke});},unsubscribeEvent:function(eventName,callback){if(!this.eventCallbacks[eventName])return;for(var i=0,l=this.eventCallbacks[eventName].length;i<l;i++){if(this.eventCallbacks[eventName][i].callback==callback){this.eventCallbacks[eventName].splice(i,1);return;}}},publishEvent:function(eventName,response){var callbacks=this.eventCallbacks[eventName];response=(response||{});response.status='success';response.eventName=eventName;if(callbacks&&callbacks.length){for(var i=callbacks.length-1;i>=0;i--){if(callbacks[i]){if(callbacks[i].callback){callbacks[i].callback(response);}
if(!callbacks[i].keepEvent){this.unsubscribeEvent(eventName,callbacks[i].callback);}}}}}};afAdScripts={log:function(s){if(false&&typeof(console)!='undefined'&&console.log)console.log(s);},logError:function(n,d){afAdScripts.logError.img=new Image();afAdScripts.logError.img.src='/wo'+'rld/js'+'_err'+'pix.a'+'sp'+'?n='+n+(d?'&d='+encodeURIComponent(d):'')+'&tmstmp='+Math.round(Math.random()*99999);},addEvent:function(elt,event,listener,capture){if(elt&&elt.addEventListener){elt.addEventListener(event,listener,capture);return true;}else if(elt&&elt.attachEvent){var d=elt.attachEvent('on'+event,listener);return d;}else{var oldListener=elt['on'+event];elt['on'+event]=function(e){if(oldListener)oldListener(e);return listener(e);}
return oldListener;}},windowSize:function(){var w=window,e=document.documentElement,b=document.body;var width=(w.innerWidth?w.innerWidth:(e&&e.clientWidth?e.clientWidth:(b&&b.clientWidth?b.clientWidth:0)));var height=(w.innerHeight?w.innerHeight:(e&&e.clientHeight?e.clientHeight:(b&&b.clientHeight?b.clientHeight:0)));var left=(w.pageXOffset?w.pageXOffset:(e&&e.scrollLeft?e.scrollLeft:(b&&b.scrollLeft?b.scrollLeft:0)));var top=(w.pageYOffset?w.pageYOffset:(e&&e.scrollTop?e.scrollTop:(b&&b.scrollTop?b.scrollTop:0)));return{l:left,t:top,r:left+width,b:top+height,w:width,h:height};},documentSize:function(){var b=top.document.body,e=top.document.documentElement;var width=Math.max(b.scrollWidth,e.scrollWidth,b.offsetWidth,e.offsetWidth,b.clientWidth,e.clientWidth)
var height=Math.max(b.scrollHeight,e.scrollHeight,b.offsetHeight,e.offsetHeight,b.clientHeight,e.clientHeight)
return{w:width,h:height};},findPos:function(o){if(!o||o==document.body)return{l:0,t:0};var l=t=0,b=document.body,w=o.offsetWidth,h=o.offsetHeight;if(o.offsetParent){l=o.offsetLeft-o.scrollLeft;t=o.offsetTop-o.scrollTop;while(o=o.offsetParent){l+=o.offsetLeft-(o!=b?o.scrollLeft:0);t+=o.offsetTop-(o!=b?o.scrollTop:0);}}
return{l:l,t:t,r:l+w,b:t+h,w:w,h:h};}};af_seealso={onload_done:false,pageid:0,target:'',domain:'',url:'/world/semantic/ifr_video.asp',init:function(o){afAdScripts.logError(2000,'af_seealso still used');var m=document.getElementById('afsa_VidMenu');if(m){l=m.childNodes;if(l){if(o&&!isNaN(o))af_seealso.pageid=o;if(o&&o.pageid)af_seealso.pageid=o.pageid;if(o&&o.target)af_seealso.target=o.target;if(o&&o.domain)af_seealso.domain=o.domain;if(o&&o.url)af_seealso.url=o.url;af_seealso.prevItem=l[0];for(var i=0;i<l.length;i++){afAdScripts.addEvent(l[i],'click',function(){af_seealso.play(this,false);af_seealso.prevItem.className='item';this.className='item selected';af_seealso.prevItem=this;var t=document.getElementById('afsa_title');if(t){if(t.href){var link=this.getElementsByTagName('a')[0];if(link){t.href=link.href;t.innerHTML=link.getElementsByTagName('span')[0].innerHTML;}}else{t.innerHTML=t.innerHTML.substr(0,t.innerHTML.indexOf(': ')+2)+this.getElementsByClassName('label')[0].innerHTML;}}},false);}
if(!af_seealso.autoplay_disabled){afAdScripts.addEvent(window,'load',function(){af_seealso.onload_done=true;af_seealso.autoplay();},false);afAdScripts.addEvent(window,'scroll',function(){af_seealso.autoplay();},false);}else{af_seealso.onload_done=true;}}}},autoplay:function(force){if(!af_seealso.autoplay_done&&af_seealso.onload_done){if(typeof(force)!='boolean')force=false;if(af_seealso.autoplay_disabled&&!force)return;var p=document.getElementById('afsa_container');if(p){var w=afAdScripts.windowSize(),i=afAdScripts.findPos(p);if(force||(w&&i&&w.l<=i.l&&w.r>=i.r&&w.t<=i.t&&w.b>=i.b)){af_seealso.autoplay_done=true;var m=document.getElementById('afsa_VidMenu');if(m)first=m.firstChild;if(first)af_seealso.play(first,!force);}}}},play:function(o,autoplay){var c=document.getElementById('afsa_container');if(c){var f=document.getElementById('afsa_iframe');if(!f){f=document.createElement('iframe');f.setAttribute('id','afsa_iframe');f.setAttribute('scrolling','no');f.setAttribute('frameborder',0);f.setAttribute('width','100%');f.setAttribute('height','100%');c.innerHTML='';c.appendChild(f);}
if(o){f.setAttribute('src',(af_seealso.domain?'//'+af_seealso.domain:'')
+af_seealso.url
+'?url='+encodeURIComponent(o.getAttribute('url'))
+'&w='+o.getAttribute('w')
+'&h='+o.getAttribute('h')
+'&rid='+o.getAttribute('rid')
+'&pubp='+af_seealso.pageid
+'&pubt='+encodeURIComponent(sas_target+';'+af_seealso.target+';autoplay='+autoplay)
+'&pubd='+(af_seealso.disable?1:0)
+'&spid='+o.getAttribute('spid')
+'&t='+encodeURIComponent(o.getAttribute('t'))
+'&ts='+Math.floor(Math.random()*100000));}
af_ua_trackEvent('SeeAlsoVideo','IframeSetting',autoplay?'autoplay':'userplay',null,true);}}};
