var af_popup={init:function(){this.init_done=true;this.global=document.createElement('div');this.global.style.display='none';this.global.style.bottom='0';this.global.style.left='0';this.global.style.right='0';this.global.style.top='0';this.global.style.overflow='hidden';this.global.style.position='fixed';this.global.style.zIndex='99999998';this.global.style.overflowY='auto';this.global.innerHTML='';document.body.appendChild(this.global);this.background=document.createElement('div');this.background.style.backgroundColor='#FFFFFF';this.background.style.opacity='0.7';this.background.style.position='absolute';this.background.style.top='0';this.background.style.left='0';this.background.style.width=document.body.clientWidth;this.background.style.height='100%';this.background.innerHTML='';this.global.appendChild(this.background);this.container=document.createElement('div');this.container.style.backgroundColor='#FFFFFF';this.container.style.position='absolute';this.container.style.boxShadow='0 0 10px rgba(0, 0, 0, 0.2)';this.container.style.webkitBoxShadow='0 0 10px rgba(0, 0, 0, 0.2)';this.container.style.mozBoxShadow='0 0 10px rgba(0, 0, 0, 0.2)';this.container.style.msBoxShadow='0 0 10px rgba(0, 0, 0, 0.2)';this.container.innerHTML='<span class="icon icon-close-btn" '+'style="position:absolute; top: -14px; right: -14px; width: 10px; height: 10px; padding:10px; background-color: #951f60; line-height: 10px; color: white; cursor:pointer; border-radius: 15px;"'+'onclick="af_popup.end(false)"></span>'+'<iframe id="af_popup_iframe" src="/shim.gif" scrolling=no frameborder=0></iframe>';this.global.appendChild(this.container);this.iframe=document.getElementById('af_popup_iframe');af_addEvent(window,'resize',function(){af_popup.resize();},false);af_addEvent(this.background,'click',function(){af_popup.end(false);},false);af_shortcuts.add(27,function(){af_popup.hide();});},show:function(w,h,url,successCallback){if(!this.init_done){this.init();}
this.url=url;this.successCallback=successCallback;this.global.style.display='';url+=((url.indexOf('?')>0)?'&':'?')+'af_popup=1';this.iframe.src=url;w=(typeof w==='undefined')?'400':w;h=(typeof h==='undefined')?'300':h;this.resize(w,h);var scrollbarSize=17;document.body.style.marginRight=scrollbarSize+'px';document.body.style.overflow='hidden';this.isShown=true;},end:function(success){this.hide();if(success&&typeof this.successCallback==='function'){this.successCallback();}},hide:function(){if(this.isShown){this.isShown=false;this.global.style.display='none';document.body.style.marginRight='0px';document.body.style.overflow='visible';this.iframe.src='/shim.gif';}},resize:function(w,h){if(this.iframe){this.w=(typeof w==='undefined')?this.w:w;this.h=(typeof h==='undefined')?this.h:h;this.iframe.width=this.w;this.iframe.height=this.h;var win=af_windowSize();this.container.style.top=Math.max(0,((win.h-this.h-20)/2))+'px';this.container.style.left=Math.max(0,((win.w-this.w-20)/2))+'px';this.background.style.width=win.w+'px';this.background.style.height=this.global.scrollHeight+'px';}}};var af_popup_social={init:function(w){this.initDone=true;this.global=document.createElement('div');this.global.style.bottom='0';this.global.style.right='0';this.global.style.position='fixed';this.global.style.zIndex='100001';this.global.style.marginRight='-'+w+'px';var transition='margin-right 0.4s ease-in-out';this.global.style['-webkit-transition']=transition;this.global.style['-moz-transition']=transition;this.global.style['-o-transition']=transition;this.global.style['transition']=transition;document.body.appendChild(this.global);this.container=document.createElement('div');this.container.style.backgroundColor='#FFFFFF';this.container.style.border='1px solid #e9ebee';this.container.innerHTML='<iframe id="af_popup_social_iframe" src="/shim.gif" scrolling=no frameborder=0></iframe>';this.global.appendChild(this.container);this.iframe=document.getElementById('af_popup_social_iframe');},show:function(url,w,h){w=(typeof w==='undefined')?'400':w;h=(typeof h==='undefined')?'300':h;if(!this.initDone){this.init(w);}
if(this.url!==url){this.url=url;this.iframe.src=url;}
if(this.h!==h){this.h=h;this.iframe.height=h;}
if(this.w!==w){this.w=w;this.iframe.width=w;}
this.global.style.marginRight='0';this.isShown=true;},hide:function(){if(this.isShown){this.isShown=false;this.global.style.marginRight='-'+this.w+'px';}}};if(typeof(Storage)!=='undefined'){var x='__storage_test__';try{localStorage.setItem(x,1);localStorage.removeItem(x);}catch(e){Storage.prototype._setItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){};}}
function af_logError(id,description){af_logError.img=new Image();af_logError.img.src='/wo'+'rld/js'+'_err'+'pix.a'+'sp'+'?n='+id+(description?'&d='+encodeURIComponent(description):'')+'&tmstmp='+Math.round(Math.random()*99999);}
function af_publish(elt,event,pubName,pubData){if(typeof elt=='string'){elt=document.getElementById(elt);}
if(elt){return af_addEvent(elt,event,function(){PubSub.publish(pubName,pubData);},false);}}
function af_removeEvent(elt,event,listener,capture){if(elt.removeEventListener){elt.removeEventListener(event,listener,capture);}else if(elt.detachEvent){elt.detachEvent("on"+event,listener);}}
function af_stopEvent(e){if(!e)e=window.event;if(e){if(e.stop)e.stop();e.preventDefault?e.preventDefault():e.returnValue=false;e.stopPropagation?e.stopPropagation():e.cancelBubble=true;}}
function af_remove(e){if(e)e.parentNode.removeChild(e);}
var af_shortcuts={list:[],init:function(){af_shortcuts.loaded=true;af_addEvent(document,'keydown',function(e){if(!e){e=window.event;}
var t=(e.srcElement?e.srcElement:e.target);if(!t.nodeName.match(/(input|textarea|select)/gi)){if(!t.className.match(/(textarea)/gi)){for(var i=0,l=af_shortcuts.list;i<l.length;i++){if(e.keyCode==l[i].key){af_stopEvent(e);l[i].func.apply(null,[e]);}}}}},false);},add:function(k,f){af_shortcuts.list.push({key:k,func:f});if(!af_shortcuts.loaded){af_shortcuts.init();}}}
function af_documentSize(){var b=document.body,e=document.documentElement;var x=Math.max(b.scrollWidth,e.scrollWidth,b.offsetWidth,e.offsetWidth,b.clientWidth,e.clientWidth);var y=Math.max(b.scrollHeight,e.scrollHeight,b.offsetHeight,e.offsetHeight,b.clientHeight,e.clientHeight);return{w:x,h:y};}
function af_smoothScroll(delay,left,top){var s=af_smoothScroll,now=(new Date()).getTime(),step=20;if(s.to){window.clearTimeout(s.to);s.to=0;}
if(delay){s.stop=now+delay;s.left=left;s.top=top;s.to=window.setTimeout(s,step);}else if(now>=s.stop){window.scrollTo(s.left,s.top);}else{var w=af_windowSize(),loop=(s.stop-now)/step;var sl=w.l+(s.left-w.l)/loop,st=w.t+(s.top-w.t)/loop;window.scrollTo(sl,st);s.to=window.setTimeout(s,step);}}
function af_throttle(fn,wait){var time=Date.now();return function(){if((time+wait-Date.now())<0){fn();time=Date.now();}}}
function af_gaqTrackEvent(category,action,opt_label,opt_value,opt_noninteraction,prefix){var opt_label=opt_label||'',opt_value=opt_value||0,opt_noninteraction=opt_noninteraction||false,prefix=prefix||'';if(typeof m_dataLayer!='undefined'){m_dataLayer.push({'event':'UA-Event','uaEventCategory':category,'uaEventAction':action,'uaEventLibelle':opt_label,'uaEventValue':opt_value,'uaEventNonInt':opt_noninteraction});}else if(typeof af_dataLayer!='undefined'){af_dataLayer.push({'event':category,'eventAction':action,'eventLabel':opt_label,'eventValue':opt_value,'eventNonInt':opt_noninteraction});}else if(typeof _gaq!='undefined'){if(prefix!==''&&prefix.substr(-1)!=='.')prefix+='.';_gaq.push([prefix+'_trackEvent',category,action,opt_label,opt_value,opt_noninteraction]);}}
function af_gaqRePush(url){var u=url?url:'/virtual'+document.location.pathname;if(typeof m_dataLayer!='undefined'){m_dataLayer.push({'event':'UA-VirtualPageView','virtualPageURL':u});}else if(typeof af_dataLayer!='undefined'){af_dataLayer.push({'event':'VirtualPageView','virtualPageURL':u});}
else if(typeof _gaq!='undefined')_gaq.push(['_trackPageview',u]);else if(typeof pageTracker!=='undefined')pageTracker._trackPageview(u);}
function af_callTracking(suffix,url,filters){if(!filters||filters&&filters['ga']){af_gaqRePush(url);}
if(!filters||filters&&filters['comscore']){if(window.COMSCORE){COMSCORE.beacon({c1:2,c2:6034949,c3:'',c4:'',c5:'',c6:'',c15:''});}}
if(!filters||filters&&filters['estat']){if(window.eStatWhap&&_eStat_Whap_loaded){eStatWhap.send();}}
if(!filters||filters&&filters['ivw']){if(window.IVW){af_callTracking.ivwImg=new Image();af_callTracking.ivwImg.src=IVW.replace(/;$/,(suffix?'-'+suffix+';':';'))
+'?r='+escape(document.referrer)+'&d='+(Math.random()*100000);}
if(window.iom&&window.iam_data){if(suffix){var ivw_cp=iam_data.cp;iam_data.cp+='-'+suffix;}
iom.c(iam_data,1);if(suffix)iam_data.cp=ivw_cp;}}
if(!filters||filters&&filters['netmetrix']){if(window.NETMX){af_callTracking.netmxImg=new Image();af_callTracking.netmxImg.src=NETMX
+'?r='+escape(document.referrer)
+'&d='+(Math.random()*100000);}}
if(!filters||filters&&filters['gemius']){if(window.gemius_hit&&window.af_gemius_identifier){gemius_hit(af_gemius_identifier);if(window.onetAds)onetAds.addKropka(true);};}
if(!filters||filters&&filters['pixlog']){if(window.pixLog){pixLog.call();}}
PubSub.publish('tracking.call');af_GBounce_data=null;}
function af_addKeyword(keyword){if(sas_target.indexOf(keyword)>=0)return;sas_target+=';'+keyword;sas_target=sas_target.replace(/;+/g,';');return sas_target;}
function af_addKeywords(keywords){for(var i=0,l=keywords.length;i<l;i++){af_addKeyword(keywords[i]);}}
function af_removeKeyword(keyword){if(sas_target.indexOf(keyword)>=0){var regex=new RegExp(keyword+'(.*?)(;|$)','g');sas_target=sas_target.replace(regex,'');}
return sas_target;}
function af_removeKeywords(keywords){for(var i=0,l=keywords.length;i<l;i++){af_removeKeyword(keywords[i]);}}
function af_refreshAds(formatIds,extraTarget,delay,pageId,forceMasterFlag,resetTimestamp,tagId){if(!(window.afAd&&window.sas&&sas.call)&&!window.onetAds&&!window.SDM_head){return false;}
formatIds=formatIds||window.sas_formatIds||'';forceMasterFlag=(typeof forceMasterFlag===undefined?true:forceMasterFlag);resetTimestamp=(typeof resetTimestamp===undefined?true:resetTimestamp);af_refreshAds.formats=af_refreshAds.formats||{};af_refreshAds.formats[formatIds]=af_refreshAds.formats[formatIds]||{nb:1,tagIds:{},canRefreshAds:true,delay:(!isNaN(delay)?delay:5000)};if(!af_refreshAds.formats[formatIds].canRefreshAds){return false;}
af_refreshAds.formats[formatIds].canRefreshAds=false;setTimeout(function(){af_refreshAds.formats[formatIds].canRefreshAds=true;},af_refreshAds.formats[formatIds].delay);if(!tagId||!af_refreshAds.formats[formatIds].tagIds[tagId]){af_refreshAds.formats[formatIds].tagIds[tagId]=true;af_refreshAds.formats[formatIds].nb++;}
var target=sas_target+(extraTarget?';'+extraTarget:'');if(tagId)target='tagid='+tagId+'t;'+target
target=target.replace(';new_ref','').replace(';new_visit','').replace(';new_page','');target=target.replace('ajax=0','').replace('ajax=1','')+';ajax=1';target=target.replace(/;+/g,';');sas_ajax=true;setTimeout(function(){var formatId,formatIdsList;if(window.onetAds){if(formatIds){if(formatIds.indexOf(',')>=0){return false;}
formatIdsList=String(formatIds).split(',');for(var i=0,l=formatIdsList.length;i<l;i++){formatId=formatIdsList[i];if(formatId){onetAds.fetchTo(document.getElementById('onet-ad-'+formatId),[formatId],function(){},0,0,0,1);}}}}else if(window.SDM_head){var documentSize=af_documentSize();formatIdsList=String(formatIds).split(',');for(var i=0,l=formatIdsList.length;i<l;i++){formatId=formatIdsList[i];var placeholderId=tagId?tagId:'sas_'+formatId;var placeholder=document.getElementById(placeholderId);if(!placeholder){placeholderId='div-gpt-ad-'+formatId;placeholder=document.getElementById(placeholderId);}
if(placeholder){var ad_definition={defnet:sas_networkId,defsite:window.sas_siteName?sas_siteName:sas_siteId,defzone:sas_pageName,size:sas_sizes[formatId],name:formatId,display:false,writeTargetDiv:false,mobile:(documentSize.w<=500?true:false),targetDiv:placeholderId};var bsl_ads=['out-of-page','banner','sky'];if(bsl_ads.indexOf(formatId)){ad_definition.adset='bsl';}
SDM_head.removeAd(formatId);SDM_head.clearTargeting();var keywords=af_dfp_formatKeywords(target).split(',');for(var j=0,len=keywords.length;j<len;j++){var keyValuePair=keywords[j].split('=');SDM_head.addTargetingForAdslot(formatId,keyValuePair[0],keyValuePair[1]);}
SDM_head.registerAd(ad_definition);SDM_head.displayAd(formatId);}}}else if(window.sas){var refresh=function(target){if(!isNaN(formatIds)){sas.call('std',{siteId:sas_siteId,pageId:(pageId?pageId:sas_pageId),formatId:formatIds,target:target,tagId:tagId},{forceMasterFlag:forceMasterFlag,resetTimestamp:resetTimestamp,async:true});}else{if(!formatIds)formatIds=sas_formatIds;afAd.refresh(formatIds,target);}};if(!window.aufbidjs){refresh(target);}
PubSub.publish('ad.refresh',{formatIds:formatIds,target:target,callback:refresh});}},50);return true;}
function af_setCookie(cname,cvalue,cminutes){cminutes=cminutes||15;var date=new Date();date.setTime(date.getTime()+(cminutes*60*1000));var expires="; expires="+date.toGMTString();document.cookie=cname+"="+cvalue+expires+"; path=/";}
function af_setCookiePerm(cname,cvalue){var oldVal=af_getCookie(cname)||'';var _afpperso;var cookiesTab=document.cookie.split(';'),ln=cookiesTab.length;for(var i=0;i<ln;i++){var x=cookiesTab[i].substr(0,cookiesTab[i].indexOf('='));var y=cookiesTab[i].substr(cookiesTab[i].indexOf('=')+1);x=x.replace(/^\s+|\s+$/g,'');if(x=='afpperso'){_afpperso=y;break;}}
if(oldVal){var j,key,getVal,newCookie='',cookiesValuesTab=y.split('&');for(j=0;j<cookiesValuesTab.length;j++){key=cookiesValuesTab[j].substr(0,cookiesValuesTab[j].indexOf('='));if(key===cname){getVal='&'+key+'='+cvalue;}else{newCookie+=newCookie===''?'':'&';newCookie+=cookiesValuesTab[j];}}
if(getVal){_afpperso=newCookie+getVal;}}else{_afpperso=_afpperso+'&'+cname+'='+cvalue;}
var d=new Date();d.setTime(d.getTime()+(10*365*24*60*60*1000));var expires='; expires='+d.toUTCString();document.cookie='afpperso='+_afpperso+
expires+'; domain='+'.'+document.domain+'; path=/';}
function af_getCookie(name){var i,x,y;var cookiesTab=document.cookie.split(';');for(i=0;i<cookiesTab.length;i++){x=cookiesTab[i].substr(0,cookiesTab[i].indexOf('='));y=cookiesTab[i].substr(cookiesTab[i].indexOf('=')+1);x=x.replace(/^\s+|\s+$/g,'');if(x=='afperso'||x=='afpperso'){var j,a,cookiesValuesTab=y.split('&');for(j=0;j<cookiesValuesTab.length;j++){a=cookiesValuesTab[j].substr(0,cookiesValuesTab[j].indexOf('='));if(a==name){return unescape(cookiesValuesTab[j].substr(cookiesValuesTab[j].indexOf('=')+1));}}}else if(x==name){return y;}}
return'';}
function af_requestGet(url,param,callback,json){var xhr=af_getXMLHttpRequest();callback=callback||null;json=json!=='undefined'?json:true;if(url.substr(0,1)==='/'){url=document.location.protocol+'//'+document.location.host+url;}
xhr.onreadystatechange=function(){if(xhr.readyState===4&&(xhr.status===200||xhr.status===0)){if(xhr.responseText){data=json?eval('('+xhr.responseText+')'):xhr.responseText;}else{data=null;}
if(callback){callback(data);}}};xhr.open('GET',(param!=='')?url+'?'+param:url,true);xhr.send(null);}
function af_requestPost(url,param,callback,json){var xhr=af_getXMLHttpRequest();callback=callback||null;json=json!=='undefined'?json:true;if(typeof af_personalHashValue!=='undefined'){param+='&personalKey='+af_personalHashValue;}
if(url.substr(0,1)=='/'){url=document.location.protocol+'//'+document.location.host+url;}
xhr.onreadystatechange=function(){if(xhr.readyState===4&&(xhr.status===200||xhr.status===0)){if(xhr.responseText){data=json?eval('('+xhr.responseText+')'):xhr.responseText;}else{data=null;}
if(callback){callback(data);}}};xhr.open('POST',url,true);xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded');xhr.setRequestHeader('X-Requested-With','XMLHttpRequest');xhr.send(param);}
function af_getXMLHttpRequest(){var xhr=null;if(window.XMLHttpRequest||window.ActiveXObject){if(window.ActiveXObject){try{xhr=new ActiveXObject('Msxml2.XMLHTTP');}catch(e){xhr=new ActiveXObject('Microsoft.XMLHTTP');}}else{xhr=new XMLHttpRequest();}}
return xhr;}
function af_urlencode(str){str=(str+'').toString();return encodeURIComponent(str).replace(/!/g,'%21').replace(/'/g,'%27').replace(/\(/g,'%28').replace(/\)/g,'%29').replace(/\*/g,'%2A').replace(/%20/g,'+');}
function af_inArray(elt,array){for(var i=0,l=array.length;i<l;i++){if(array[i]==elt)return true;}
return false;}
function af_trim(text){if(text!==undefined){return(""+text+"").replace(/(^\s*)|(\s*$)/g,"");}else{return text;}}
var _isTablet,_isMobile;function _mobileDetection(){_isTablet=false;_isMobile=false;if(navigator.userAgent.match(/(ipod|blackberry|phone|mobile|opera mini|pda|symbian|3ds|nokia|ericsson|alcatel)/gi)!=null){if(navigator.userAgent.match(/(pad|lenovo|tab|GT-P5210|GT-P5110|Nexus 7|GT-N8010|GT-P3110)/gi)!=null){_isTablet=true;}
else{_isMobile=true;}}
else if(navigator.userAgent.match(/(pad|tab|android)/gi)!=null){_isTablet=true;}}
function af_isMobile(){if(typeof _isMobile!=='undefined'){return _isMobile;}
_mobileDetection();return _isMobile;}
function af_isTablet(){if(typeof _isTablet!=='undefined'){return _isTablet;}
_mobileDetection();return _isTablet;}
function af_getTarget(e){if(typeof e!=='undefined'){var _t=e.target||e.srcElement;}else{return'undefined';}
while(_t.classList.contains('action-parent')){_t=_t.parentNode;}
return _t;}
function af_getParent(e,pattern){var ret=null;if(e.nodeName=='HTML'){return null;}
if(typeof e!=='undefined'){var parent=e.parentNode;if(typeof pattern==='undefined'){ret=parent;}
else{var patterns=pattern.split(' ');var firstPattern=patterns.shift();var newPattern=patterns.join(' ');if(firstPattern.indexOf('.')===0){var cssClassLists=firstPattern.split('.');cssClassLists.shift();var cssFound=0
for(var n=0;n<cssClassLists.length;n++){if(e.classList.contains(cssClassLists[n])){cssFound++;}}
if(cssFound===cssClassLists.length){if(newPattern.length){ret=af_getParent(parent,newPattern);}else{ret=e;}}else{ret=af_getParent(parent,pattern);}}
else if(firstPattern.indexOf('#')===0){var id=firstPattern.substring(1);if(e.id===id){if(newPattern.length){ret=af_getParent(parent,newPattern);}else{ret=e;}}
else{ret=af_getParent(parent,pattern);}}
else{if(e.nodeType===1&&firstPattern.toUpperCase()===e.nodeName){if(newPattern.length){ret=af_getParent(parent,newPattern);}else{ret=e;}}
else{ret=af_getParent(parent,pattern);}}}
return ret;}
else{return undefined;}}
var AfHttpRequest=(function(){var getXMLHttpRequest=function(){var xhr=null;if(window.XMLHttpRequest||window.ActiveXObject){if(window.ActiveXObject){try{xhr=new ActiveXObject('Msxml2.XMLHTTP');}catch(e){xhr=new ActiveXObject('Microsoft.XMLHTTP');}}else{xhr=new XMLHttpRequest();}}
return xhr;};var getRequest=function(callback,json){var xhr=af_getXMLHttpRequest();callback=callback||null;json=json!=='undefined'?json:true;xhr.onreadystatechange=function(){if(xhr.readyState===4&&(xhr.status===200||xhr.status===201||xhr.status===202||xhr.status===204||xhr.status===0)){if(xhr.responseText){data=json?eval('('+xhr.responseText+')'):xhr.responseText;}else{data=null;}
if(callback){callback(data,xhr);}}};return xhr;};var getAbsoluteUrl=function(url){if(url.substr(0,1)==='/'){url=document.location.protocol+'//'+document.location.host+url;}
return url;};var getData=function(param){var data=param!=='undefined'?param:'';if(typeof af_personalHashValue!=='undefined'){data+='&personalKey='+af_personalHashValue;}
return data;};return{get:function(url,param,callback,json){var xhr=getRequest(callback,json);var absoluteUrl=getAbsoluteUrl(url);xhr.open('GET',(param!=='')?absoluteUrl+'?'+param:absoluteUrl,true);xhr.send(null);},post:function(url,param,callback,json){var xhr=getRequest(callback,json);var absoluteUrl=getAbsoluteUrl(url);var data=typeof param==='object'?JSON.stringify(param):getData(param);var contentType=typeof param==='object'?'application/json':'application/x-www-form-urlencoded';xhr.open('POST',absoluteUrl,true);xhr.setRequestHeader('Content-Type',contentType);xhr.setRequestHeader('X-Requested-With','XMLHttpRequest');xhr.send(data);},postMultipart:function(url,param,callback,json){var xhr=getRequest(callback,json);var absoluteUrl=getAbsoluteUrl(url);var data=getData(param);xhr.open('POST',absoluteUrl,true);xhr.setRequestHeader('X-Requested-With','XMLHttpRequest');xhr.send(data);},put:function(url,param,callback,json){var xhr=getRequest(callback,json);var absoluteUrl=getAbsoluteUrl(url);var data=typeof param==='object'?JSON.stringify(param):getData(param);var contentType=typeof param==='object'?'application/json':'application/x-www-form-urlencoded';xhr.open('PUT',absoluteUrl,true);xhr.setRequestHeader('Content-Type',contentType);xhr.setRequestHeader('X-Requested-With','XMLHttpRequest');xhr.send(data);},patch:function(url,param,callback,json){var xhr=getRequest(callback,json);var absoluteUrl=getAbsoluteUrl(url);var data=typeof param==='object'?JSON.stringify(param):getData(param);var contentType=typeof param==='object'?'application/json':'application/x-www-form-urlencoded';xhr.open('PATCH',absoluteUrl,true);xhr.setRequestHeader('Content-Type',contentType);xhr.setRequestHeader('X-Requested-With','XMLHttpRequest');xhr.send(data);},del:function(url,param,callback,json){var xhr=getRequest(callback,json);var absoluteUrl=getAbsoluteUrl(url);xhr.open('DELETE',(param!=='')?absoluteUrl+'?'+param:absoluteUrl,true);xhr.send(null);}};})();function connectedUserOnlyAction(e){var _t=af_getTarget(e);PubSub.publish('connectedUsersOnly',_t);af_stopEvent(e);var href=this.href||this.getAttribute('data-href')||window.location.href;var url;if(document.domain!=='marmiton.org'){url='/reloaded/users/login?destUrl=';}else{url='/espace-perso/login.aspx?returnUrl=';}
window.location.href='https://www.'+document.domain+url+encodeURIComponent(href);return false;}
if(typeof(af_addEvent)!=='undefined'){if(af_getCookie('cu')===''&&typeof document.getElementsByClassName!=='undefined'){var elements=document.getElementsByClassName('connectedUsersOnly');for(var i=elements.length-1;i>=0;i--){var element=elements[i];element.classList.remove('connectedUsersOnly');if(element.onclick){element.previousOnclick=element.onclick;element.onclick=null;}
af_addEvent(element,'click',af_bind(element,connectedUserOnlyAction),true);}}}
function af_canRefreshAds(){return(typeof window.top.af_stopRefreshAds!=='undefined')?!window.top.af_stopRefreshAds:true;}
(function(window){"use strict";var $=function(callback){registerOrRunCallback(callback);bindReady();},document=window.document,readyBound=false,callbackQueue=[],registerOrRunCallback=function(callback){if(typeof callback==="function"){callbackQueue.push(callback);}},DOMReadyCallback=function(){while(callbackQueue.length){(callbackQueue.shift())();}
registerOrRunCallback=function(callback){callback();};},DOMContentLoaded=function(){if(document.addEventListener){document.removeEventListener("DOMContentLoaded",DOMContentLoaded,false);}else{document.detachEvent("onreadystatechange",DOMContentLoaded);}
DOMReady();},DOMReady=function(){if(!$.isReady){if(!document.body){return setTimeout(DOMReady,1);}
$.isReady=true;DOMReadyCallback();}},bindReady=function(){var toplevel=false;if(readyBound){return;}
readyBound=true;if(document.readyState!=="loading"){DOMReady();}
if(document.addEventListener){document.addEventListener("DOMContentLoaded",DOMContentLoaded,false);window.addEventListener("load",DOMContentLoaded,false);}else if(document.attachEvent){document.attachEvent("onreadystatechange",DOMContentLoaded);window.attachEvent("onload",DOMContentLoaded);try{toplevel=window.frameElement==null;}catch(e){}
if(document.documentElement.doScroll&&toplevel){doScrollCheck();}}},doScrollCheck=function(){if($.isReady){return;}
try{document.documentElement.doScroll("left");}catch(error){setTimeout(doScrollCheck,1);return;}
DOMReady();};$.isReady=false;window.jquery$=$;})(window);
(function(root,factory){'use strict';if(typeof define==='function'&&define.amd){define(['exports'],factory);}else if(typeof exports==='object'){factory(exports);}else{var PubSub={};root.PubSub=PubSub;factory(PubSub);}}((typeof window==='object'&&window)||this,function(PubSub){'use strict';var messages={},lastUid=-1;function hasKeys(obj){var key;for(key in obj){if(obj.hasOwnProperty(key)){return true;}}
return false;}
function throwException(ex){return function reThrowException(){throw ex;};}
function callSubscriberWithDelayedExceptions(subscriber,message,data){try{subscriber(message,data);}catch(ex){setTimeout(throwException(ex),0);}}
function callSubscriberWithImmediateExceptions(subscriber,message,data){subscriber(message,data);}
function deliverMessage(originalMessage,matchedMessage,data,immediateExceptions){var subscribers=messages[matchedMessage],callSubscriber=immediateExceptions?callSubscriberWithImmediateExceptions:callSubscriberWithDelayedExceptions,s;if(!messages.hasOwnProperty(matchedMessage)){return;}
for(s in subscribers){if(subscribers.hasOwnProperty(s)){callSubscriber(subscribers[s],originalMessage,data);}}}
function createDeliveryFunction(message,data,immediateExceptions){return function deliverNamespaced(){var topic=String(message),position=topic.lastIndexOf('.');deliverMessage(message,message,data,immediateExceptions);while(position!==-1){topic=topic.substr(0,position);position=topic.lastIndexOf('.');deliverMessage(message,topic,data,immediateExceptions);}};}
function messageHasSubscribers(message){var topic=String(message),found=Boolean(messages.hasOwnProperty(topic)&&hasKeys(messages[topic])),position=topic.lastIndexOf('.');while(!found&&position!==-1){topic=topic.substr(0,position);position=topic.lastIndexOf('.');found=Boolean(messages.hasOwnProperty(topic)&&hasKeys(messages[topic]));}
return found;}
function publish(message,data,sync,immediateExceptions){var deliver=createDeliveryFunction(message,data,immediateExceptions),hasSubscribers=messageHasSubscribers(message);if(!hasSubscribers){return false;}
if(sync===true){deliver();}else{setTimeout(deliver,0);}
return true;}
PubSub.publish=function(message,data){return publish(message,data,false,PubSub.immediateExceptions);};PubSub.publishSync=function(message,data){return publish(message,data,true,PubSub.immediateExceptions);};PubSub.subscribe=function(message,func){if(typeof func!=='function'){return false;}
if(!messages.hasOwnProperty(message)){messages[message]={};}
var token='uid_'+String(++lastUid);messages[message][token]=func;return token;};PubSub.clearAllSubscriptions=function clearAllSubscriptions(){messages={};};PubSub.clearSubscriptions=function clearSubscriptions(topic){var m;for(m in messages){if(messages.hasOwnProperty(m)&&m.indexOf(topic)===0){delete messages[m];}}};PubSub.unsubscribe=function(value){var isTopic=typeof value==='string'&&messages.hasOwnProperty(value),isToken=!isTopic&&typeof value==='string',isFunction=typeof value==='function',result=false,m,message,t;if(isTopic){delete messages[value];return;}
for(m in messages){if(messages.hasOwnProperty(m)){message=messages[m];if(isToken&&message[value]){delete message[value];result=value;break;}
if(isFunction){for(t in message){if(message.hasOwnProperty(t)&&message[t]===value){delete message[t];result=true;}}}}}
return result;};}));
af_utils={log:function(s){if(false&&typeof(console)!='undefined'&&console.log)console.log(s);},logError:function(n,d){af_utils.logError.img=new Image();af_utils.logError.img.src='/wo'+'rld/js'+'_err'+'pix.a'+'sp'+'?n='+n+(d?'&d='+encodeURIComponent(d):'')+'&tmstp='+Math.round(Math.random()*99999);},addEvent:function(elt,event,listener,capture){if(elt&&elt.addEventListener){elt.addEventListener(event,listener,capture);return true;}else if(elt&&elt.attachEvent){var d=elt.attachEvent('on'+event,listener);return d;}else{var oldListener=elt['on'+event];elt['on'+event]=function(e){if(oldListener)oldListener(e);return listener(e);}
return oldListener;}},removeEvent:function(elt,event,listener,capture){if(elt.removeEventListener){elt.removeEventListener(event,listener,capture);}else if(elt.detachEvent){elt.detachEvent("on"+event,listener);}},stickyBar:{list:[],state:0,init:function(){var sB=af_utils.stickyBar;window.onscroll=function(){if(sB.state){window.clearTimeout(sB.state);sB.state=0;}
sB.state=window.setTimeout(sB.updateElements,100);}},updateElements:function(){y=(document.documentElement&&document.documentElement.scrollTop)||window.pageYOffset||document.body.scrollTop;var fromTop=0;for(var i=0,l=af_utils.stickyBar.list;i<l.length;i++){if(y>l[i].t){l[i].elem.className=l[i].stickyClass+' fixed';l[i].elem.style.top=fromTop+'px';var temp=af_utils.findPos(l[i].elem);fromTop+=temp.h;temp=null;}else{l[i].elem.className=l[i].stdClass;l[i].elem.style.top='';}}},add:function(elemID,stdClass,stickyClass,fromTop){if(fromTop==undefined)fromTop=0;var obj={elem:document.getElementById(elemID),b:0,stdClass:stdClass,stickyClass:stickyClass}
if(fromTop>0){obj.t=fromTop;}else{var t=af_utils.findPos(obj.elem);obj.t=t.t;}
af_utils.stickyBar.list.push(obj);}},stopEvent:function(e){if(!e)e=window.event;if(e){e.preventDefault?e.preventDefault():e.returnValue=false;e.stopPropagation?e.stopPropagation():e.cancelBubble=true;}},shortcuts:{list:[],init:function(){af_utils.shortcuts.loaded=true;af_utils.addEvent(document,'keydown',function(e){if(!e)e=window.event;var t=(e.srcElement?e.srcElement:e.target);if(!t.nodeName.match(/(input|textarea|select)/gi)){if(!t.className.match(/(textarea)/gi)){for(var i=0,l=af_utils.shortcuts.list;i<l.length;i++){if(e.keyCode==l[i].key){af_utils.stopEvent(e);l[i].func.apply();}}}}},false);},add:function(k,f){af_utils.shortcuts.list.push({key:k,func:f});if(!af_utils.shortcuts.loaded){af_utils.shortcuts.init();}}},popup:{init:function(){this.init_done=true;this.global=document.createElement('div');this.global.style.display='none';this.global.style.bottom='0';this.global.style.left='0';this.global.style.right='0';this.global.style.top='0';this.global.style.overflow='hidden';this.global.style.position='fixed';this.global.style.zIndex='99999998';this.global.style.overflowY='auto';this.global.innerHTML='';document.body.appendChild(this.global);this.background=document.createElement('div');this.background.style.backgroundColor='#FFFFFF';this.background.style.opacity='0.7';this.background.style.position='absolute';this.background.style.top='0';this.background.style.left='0';this.background.style.width=document.body.clientWidth;this.background.style.height='100%';this.background.innerHTML='';this.global.appendChild(this.background);this.container=document.createElement('div');this.container.style.backgroundColor='#FFFFFF';this.container.style.border='5px solid transparent';this.container.style.padding='20px 0';this.container.style.position='absolute';this.container.style.boxShadow='0 0 10px #000000';this.container.style.webkitBoxShadow='0 0 10px #000000';this.container.style.mozBoxShadow='0 0 10px #000000';this.container.style.msBoxShadow='0 0 10px #000000';this.container.innerHTML='<img src="/world/static/communaute/forum/images/img-fermer.png" '
+'  style="position:absolute; top: 0; right: 0; padding:10px; cursor:pointer" '
+'  onclick="af_utils.popup.end(false)" />'
+'<iframe id="af_popup_iframe" src="/shim.gif" scrolling=no frameborder=0></iframe>';this.global.appendChild(this.container);this.iframe=document.getElementById('af_popup_iframe');af_utils.addEvent(window,'resize',function(){af_utils.popup.resize();},false);af_utils.addEvent(this.background,'click',function(){af_utils.popup.end(false);},false);af_utils.shortcuts.add(27,function(){af_utils.popup.hide();});},show:function(w,h,url,successCallback){if(!this.init_done)this.init();this.url=url;this.successCallback=successCallback;this.global.style.display='';url+=((url.indexOf('?')>0)?'&':'?')+'af_utils.popup=1'
this.iframe.src=url;w=(typeof w=='undefined')?'400':w;h=(typeof h=='undefined')?'300':h;this.resize(w,h);var scrollbarSize=17;document.body.style.marginRight=scrollbarSize+'px';document.body.style.overflow='hidden';},end:function(success){this.hide();if(success&&typeof this.successCallback=='function'){this.successCallback();}},hide:function(){this.global.style.display='none';document.body.style.marginRight='0px';document.body.style.overflow='visible';this.iframe.src='/shim.gif';},resize:function(w,h){this.w=(typeof w=='undefined'||w<this.w)?this.w:w;this.h=(typeof h=='undefined')?this.h:h;this.iframe.width=this.w;this.iframe.height=this.h;var win=af_utils.windowSize();this.container.style.top=Math.max(0,((win.h-this.h-20)/2))+'px';this.container.style.left=Math.max(0,((win.w-this.w-20)/2))+'px';this.background.style.width=win.w+'px';this.background.style.height=this.global.scrollHeight+'px';}},documentSize:function(){var b=document.body,e=document.documentElement;var x=Math.max(b.scrollWidth,e.scrollWidth,b.offsetWidth,e.offsetWidth,b.clientWidth,e.clientWidth)
var y=Math.max(b.scrollHeight,e.scrollHeight,b.offsetHeight,e.offsetHeight,b.clientHeight,e.clientHeight)
return{w:x,h:y};},windowSize:function(){var i=window,e=document.documentElement,b=document.body;var w=(i.innerWidth?i.innerWidth:(e&&e.clientWidth?e.clientWidth:(b&&b.clientWidth?b.clientWidth:0)));var h=(i.innerHeight?i.innerHeight:(e&&e.clientHeight?e.clientHeight:(b&&b.clientHeight?b.clientHeight:0)));var l=(i.pageXOffset?i.pageXOffset:(e&&e.scrollLeft?e.scrollLeft:(b&&b.scrollLeft?b.scrollLeft:0)));var t=(i.pageYOffset?i.pageYOffset:(e&&e.scrollTop?e.scrollTop:(b&&b.scrollTop?b.scrollTop:0)));return{l:l,t:t,r:l+w,b:t+h,w:w,h:h};},findPos:function(o){if(!o||o==document.body)return{l:0,t:0};var l=t=0,b=document.body,w=o.offsetWidth,h=o.offsetHeight;if(o.offsetParent){l=o.offsetLeft-o.scrollLeft;t=o.offsetTop-o.scrollTop;while(o=o.offsetParent){l+=o.offsetLeft-(o!=b?o.scrollLeft:0);t+=o.offsetTop-(o!=b?o.scrollTop:0);}}
return{l:l,t:t,r:l+w,b:t+h,w:w,h:h};},smoothScroll:function(delay,left,top){var s=af_utils.smoothScroll,now=(new Date()).getTime(),step=20;if(s.to){window.clearTimeout(s.to);s.to=0;}
if(delay){s.stop=now+delay;s.left=left;s.top=top;s.to=window.setTimeout(s,step);}else if(now>=s.stop){window.scrollTo(s.left,s.top);}else{var w=af_utils.windowSize(),loop=(s.stop-now)/step;var sl=w.l+(s.left-w.l)/loop,st=w.t+(s.top-w.t)/loop;window.scrollTo(sl,st);s.to=window.setTimeout(s,step);}},tagsDisplay:function(show){var t=af_utils.tagsDisplay;if(!t.selects&&!show)t.selects=document.getElementsByTagName("select");af_utils.toggleVisibility(t.selects,show)
if(!t.embeds&&!show)t.embeds=document.getElementsByTagName("embed");af_utils.toggleVisibility(t.embeds,show)
if(!t.objects&&!show)t.objects=document.getElementsByTagName("object");af_utils.toggleVisibility(t.objects,show)
if(!t.iframes&&!show)t.iframes=document.getElementsByTagName("iframe");af_utils.toggleVisibility(t.iframes,show)
for(var i=0,l=af_utils.stickyBar.list;i<l.length;i++){if(l[i].elem){var o=l[i].elem;if(o)
o.style.display=(show?'':'none');}}},toggleVisibility:function(items,show){if(!items)return;if((typeof items.vis!='undefined')&&(items.vis==show))return;for(var i=0;i<items.length;i++){var o=items[i];if(!show)o.prevVisibility=''+o.style.visibility;o.style.visibility=(show?o.prevVisibility:'hidden');}
items.vis=show;},callTracking:function(suffix){try{af_gaqRePush();if(typeof COMSCORE!='undefined')COMSCORE.beacon({c1:2,c2:6034949,c3:"",c4:"",c5:"",c6:"",c15:""});if(typeof(eStatWhap)!='undefined'&&_eStat_Whap_loaded)eStatWhap.send();if(typeof(IVW)!='undefined'&&IVW!=''){af_utils.callTracking.ivwImg=new Image();af_utils.callTracking.ivwImg.src=IVW.replace(/;$/,(suffix?'-'+suffix+';':';'))+'?r='+escape(document.referrer)+'&d='+(Math.random()*100000);}
if(typeof iom!='undefined'&&typeof iam_data!='undefined'){if(suffix){var ivw_cp=iam_data.cp;iam_data.cp+='-'+suffix;}
iom.c(iam_data,1);if(suffix)iam_data.cp=ivw_cp;}
af_GBounce_data=null;}catch(e){af_utils.logError(2,e.message);}},contentClick:function(target,inherit){var p=target,l=p.getElementsByTagName('a');if(inherit)
while(p&&l.length==0){l=p.getElementsByTagName('a');p=p.parentNode;}
if(l.length)
for(var i=0;i<l.length;i++)
if(l[i].href){window.open(l[i].href,l[i].target||'_self');return;}},trim:function(text){if(text!==undefined)return(""+text+"").replace(/(^\s*)|(\s*$)/g,"");else return text;},_mobileDetection:function(){this._isMobile=false;this._isTablet=false;if(navigator.userAgent.match(/(ipod|blackberry|phone|mobile|opera mini|pda|symbian|3ds|nokia|ericsson|alcatel)/gi)!=null){if(navigator.userAgent.match(/(pad|lenovo|tab|GT-P5210|GT-P5110|Nexus 7|GT-N8010|GT-P3110)/gi)!=null){this._isTablet=true;}
else{this._isMobile=true;}}
else if(navigator.userAgent.match(/(pad|tab|android)/gi)!=null){this._isTablet=true;}},isMobile:function(){if(typeof this._isMobile!=='undefined'){return this._isMobile;}
this._mobileDetection();return this._isMobile;},isTablet:function(){if(typeof this._isTablet!=='undefined'){return this._isTablet;}
this._mobileDetection();return this._isTablet;}};if(typeof(af_lazyloading)==='undefined'){var af_lazyloading_timeout=null;var af_lazyloading_dist=200;var af_lazyloading_imgs=document.getElementsByTagName('img');af_lazyloading=function(){if(af_lazyloading_timeout==null){af_lazyloading_timeout=setTimeout(af_lazyloading_real,50);}};af_lazyloading_real=function(){var w=af_utils.windowSize();var len=af_lazyloading_imgs.length;for(var i=0;i<len;i++){var img=af_lazyloading_imgs[i];var d=img.getAttribute('data-origin');if(d&&d!=''){if(w.b+af_lazyloading_dist>=af_utils.findPos(img).b){img.src=d;img.setAttribute('data-origin','');}}}
af_lazyloading_timeout=null;};if(typeof(af_utils)!='undefined'&&af_utils.addEvent){af_utils.addEvent(window,'scroll',af_lazyloading,false);af_utils.addEvent(window,'load',af_lazyloading,false);}}
function af_zoomShow(src,w,h){if(typeof(afvid_stopVideo)!="undefined")afvid_stopVideo();winwidth=window.innerWidth?window.innerWidth:document.body.clientWidth;winheight=window.innerHeight?window.innerHeight:document.body.clientHeight;if(w>winwidth-60||h>winheight-60){cw=(winwidth-60)/w;ch=(winheight-60)/h;c=(cw>ch?ch:cw);w*=c;h*=c;}
popupContent='<img class=af_zoomContent src="'+src+'" width='+w+' height='+h+' border=0 />';af_utils.tagsDisplay(false);af_zoomWindow(popupContent,w,h);}
function af_hideAddressBar(){window.scrollTo(0,1);}
function af_goBack(){history.go(-1);af_menuHide();}
function af_menuShow(menuID){if(typeof(afvid_stopVideo)!="undefined")afvid_stopVideo();af_menuTagsShowHide(false);af_menuWindow(menuID);if(typeof(af_localMenuShowCallback)!="undefined")af_localMenuShowCallback();}
function af_bookmarkShow(bookmarkID){af_menuShow(bookmarkID);var div=document.getElementById(bookmarkID);div.style.top=window.innerHeight+window.pageYOffset-div.offsetHeight-40+'px';div.style.webkitTransitionProperty='top';div.style.webkitTransitionTimingFunction='default';div.style.webkitTransitionDuration='500ms';div.style.webkitTransform='translate3d(0, 0, 0)';}
function getViewportScrollY(){var scrollY=0;if(document.documentElement&&document.documentElement.scrollTop){scrollY=document.documentElement.scrollTop;}
else if(document.body&&document.body.scrollTop){scrollY=document.body.scrollTop;}
else if(window.pageYOffset){scrollY=window.pageYOffset;}
else if(window.scrollY){scrollY=window.scrollY;}
return scrollY;}
var af_menuBg,af_menuDiv;function af_menuWindow(menuID){if(!af_menuBg){af_menuBg=document.createElement("DIV");af_menuBg.innerHTML='&nbsp;';af_menuBg.className='af_menuBg';document.body.insertBefore(af_menuBg,document.body.firstChild);af_menuBg.onclick=af_menuHide;}
af_menuDiv=document.getElementById(menuID);;af_menuBgHeight=window.innerHeight?window.innerHeight:document.body.clientHeight;if(document.body.scrollHeight>af_menuBgHeight)af_menuBgHeight=document.body.scrollHeight
af_menuBg.style.visibility='visible';af_menuBg.style.height=af_menuBgHeight+"px";af_menuDiv.style.display='';}
function af_menuHide(){if(typeof(afvid_stopVideo)!="undefined")afvid_stopVideo();if(af_menuBg){af_menuBg.style.visibility='hidden';af_menuBg.style.height="0px";}
if(af_menuDiv){af_menuDiv.style.display='none';}
af_menuTagsShowHide(true);}
function af_menuTagsShowHide(show){af_utils.tagsDisplay(show);if(!af_menuTagsShowHide.videos&&!show)af_menuTagsShowHide.videos=document.getElementsByTagName("video");af_utils.toggleVisibility(af_menuTagsShowHide.videos,show)}
function afm_gaqRePush(url){af_gaqRePush(url);}
window.addEventListener('message',af_receiveMessage,false);function af_receiveMessage(e){if(e.origin==document.location.protocol+'//'+document.location.host){if(e.data=='registration_ok'){document.location.hash='registration_ok';}}}
function af_gaqRePush(url){var u=url?url:document.location.href.replace(/^http(s)?:\/\/.*?\//gi,'/virtual/');af_ua_trackVirtualPV(u);}
function af_gaqTrackEvent(category,action,opt_label,opt_value,opt_noninteraction,prefix){af_ua_trackEvent(category,action,opt_label,opt_value,opt_noninteraction,prefix);}
var af_loginFrame=null;function af_toggleLoginFrame(params){if(params==undefined)params='';if(params=='')params='desturl='+escape(document.location.href)
if(typeof(SITEID)!='undefined'&&(SITEID<=6||SITEID==8||SITEID==25||SITEID>=29)){if([1,6,8].indexOf(SITEID)===-1&&document.location.pathname!='/'){document.location='/#connect,'+params
return false;}}else{document.location='/world/communaute/connexion/quickconnect.asp?'+params;return false;}
if(af_loginFrame==null){af_loginFrame=document.createElement('div');var e=document.getElementById('af_btnConnect');if(e==null)e=document.getElementById('af_userbarlog').firstChild.nextSibling;var text=e.innerHTML;af_loginFrame.innerHTML='<div class="af_navUserBarPopUpLink">'+'<a href="#" onclick="return af_toggleLoginFrame()">'+text+'</a></div>'+'<iframe id="af_ifrUserConnect" class="af_navUserBarPopUpConnect" '+' src="/world/communaute/users/popup.asp?'+params+'" '+' width="1" height="0" scrolling="no" FRAMEBORDER="0" allowtransparency="true"></iframe>';af_loginFrame.style.display='none';e=document.getElementById('af_displayPopup')
if(e==null)e=document.getElementById('af_headerUserBarLogin');e.appendChild(af_loginFrame);}
if(af_loginFrame.style.display=='none'){af_loginFrame.style.display='';var pos=af_utils.findPos(document.getElementById('af_btnConnect'));af_utils.smoothScroll(400,0,pos.t);}else{af_loginFrame.style.display='none';}
if(typeof(SITEID)!='undefined'&&SITEID==4){aff_ivw('');}
return false;}
function aff_ivw(suffix){if(typeof IVW!='undefined'&&IVW!=''){aff_ivw.ivw=new Image();aff_ivw.ivw.src=IVW.replace(/;$/,(suffix?'-'+suffix+';':';'))+'?r='+escape(document.referrer)+'&d='+(Math.random()*100000);}
if(typeof iom!='undefined'&&typeof iam_data!='undefined'){if(suffix){var ivw_cp=iam_data.cp;iam_data.cp+='-'+suffix;}
iom.c(iam_data,1);if(suffix)iam_data.cp=ivw_cp;}
if(typeof OEWA!='undefined'&&OEWA!=''){aff_ivw.oewa=new Image();aff_ivw.oewa.src=OEWA+'?r='+escape(document.referrer)+'&d='+(Math.random()*100000);}}
function af_firstLoginFrame(msg,desturl){document.getElementById('af_ifrUserConnect').src='/world/communaute/users/popup.asp?msg='+msg+'&desturl='+desturl;}
function aff_inscription(desturl){var oImg=new Image();oImg.src='http://network.aufeminin.com/call/pubimppixel/5295084/'+Math.floor(Math.random()*100000)+1;oImg.width='0';oImg.height='0';oImg.border='0';oImg.style.position='absolute';document.body.appendChild(oImg);top.location.href='/world/communaute/users/inscription.asp?mode=full&desturl='+desturl;}
var reg=new RegExp('^#connect,(.+)','i');if(matches=reg.exec(location.hash)){if(SITEID==1){var oImg=new Image();oImg.src='http://network.aufeminin.com/call/pubimppixel/7837436/'+Math.floor(Math.random()*100000)+1;oImg.width='0';oImg.height='0';oImg.border='0';oImg.style.position='absolute';document.body.appendChild(oImg);}
af_toggleLoginFrame(matches[1]);}
var reg=new RegExp('^#login,(.+)','i');if(matches=reg.exec(location.hash)){var params=matches[1];destUrl=params.split("=");var destUrl=destUrl[1];if(typeof(SITEID)!='undefined'&&(SITEID==4||SITEID==26)){if(af_utils!='undefined'){af_utils.popup.show(500,500,'/reloaded/users/login?'+params,function(){window.location=destUrl;});}}}
var reg=new RegExp('^#register,(.+)','i');if(matches=reg.exec(location.hash)){var params=matches[1];destUrl=params.split("=");var destUrl=destUrl[1];if(typeof(SITEID)!='undefined'&&(SITEID==4||SITEID==26)){if(af_utils!='undefined'){af_utils.popup.show(500,500,'/reloaded/users/register?'+params,function(){window.location=destUrl;});}}}
var af_GBounce={open:false,displayed:false,data:[],sourceData:1,init:function(){this.data=af_GBounce_data;if(this.sourceData===1){var links=this.getFirstElementWithClassName('afsa_relLinks','div');if(links){var splitDomain=document.location.href;splitDomain=splitDomain.replace('http://','');splitDomain=splitDomain.split('/')[0];splitDomain=splitDomain.split('.');var domain='';for(var i=splitDomain.length;i--;i>=0){if(domain!==''){domain='.'+domain;}
domain=splitDomain[i]+domain;if(splitDomain[i].length>4){break;}}
var l=links.getElementsByTagName('a');var indexData=0;for(var j=l.length-1;j>=0;j--){var href=l[j].href.replace(/#.*$/,'');if(href.indexOf(domain)>=0){if(href.replace('http://','').split('/')[1]!==''){this.data.unshift({'url':href,'title':l[j].innerHTML,'imgSrc':'/world/semantic/link2acc.asp?acc=Accroche228x140&link='+escape(href)});indexData++;}}}}}
while(this.data.length>6){this.data.pop();}
if(this.data.length!=6){this.displayed=true;return;}
for(var k=0;k<this.data.length;k++){this.data[k].img=new Image();this.data[k].img.src=this.data[k].imgSrc;}},getFirstElementWithClassName:function(classname,objectType){var e;if(document.getElementsByClassName){e=document.getElementsByClassName(classname);if(e&&e.length>0){return e[0];}}else{e=document.getElementsByTagName(objectType);for(var i=0;i<e.length;i++){if(e[i].className==classname){return e[i];}}}
return null;},generate:function(){var html='';for(var i=0;i<this.data.length;i++){var item=this.data[i];var onclick=' onclick="af_GBounce.onClick('+i+')"';if(i==3){html+='<div class="af_bpopup_spacer"></div>';}
html+='<div>';var url=item.url;html+='<a href="'+url+'" title="'+item.title+'"'+onclick+'>'+'<img src="'+item.img.src+'" />'+'</a>'+'<a href="'+url+'" title="'+item.title+'"'+onclick+'>'+item.title+'</a>'+'<a href="'+url+'"'+onclick+'>'+this.popupPlusDe+'</a>';html+='</div>';}
html+='<div></div>';return html;},onMouseOut:function(e){if(!af_GBounce.displayed){e=e?e:window.event;var from=e.relatedTarget||e.toElement;if((!from||from.nodeName=='HTML')&&e.clientY<=0){height=af_GBounce.data.length==3?201:450;af_GBounce.popup.show(739,height,af_GBounce.generate(),af_GBounce.popupTitle,'gBounceContentDiv');af_GBounce.displayed=true;}}},onClick:function(index){af_gaqTrackEvent('GoogleBouncer','Click','v'+af_GBounce.sourceData,index);},popup:{init:function(){this.init_done=true;this.global=document.createElement('div');this.global.style.display='none';this.global.style.bottom='0';this.global.style.left='0';this.global.style.right='0';this.global.style.top='0';this.global.style.overflow='auto';this.global.style.position='fixed';this.global.style.zIndex='99999998';this.global.innerHTML='';document.body.appendChild(this.global);this.background=document.createElement('div');this.background.className='gBouncerBackground';this.background.innerHTML='';this.global.appendChild(this.background);this.container=document.createElement('div');this.container.innerHTML='<img src="/world/static/communaute/forum/images/img-fermer.png" '
+'  onclick="af_GBounce.popup.hide()" />'
+'<div id="af_gbounce_content"></div>';this.global.appendChild(this.container);this.content=document.getElementById('af_gbounce_content');af_utils.addEvent(window,'resize',function(){af_GBounce.popup.resize();},false);af_utils.addEvent(this.background,'click',function(){af_GBounce.popup.hide();},false);af_utils.shortcuts.add(27,function(){af_GBounce.popup.hide();});},show:function(w,h,content,title,popupContainerClass){if(!this.init_done)this.init();this.w=w;this.h=h;this.global.style.display='';this.content.innerHTML='<div style="height:'+h+'px; width:'+w+'px;">'
+'<div>'+title+'</div>'
+content+'</div>';this.container.className=popupContainerClass;this.resize();var scrollbarSize=17;document.body.style.marginRight=scrollbarSize+'px';document.body.style.overflow='hidden';af_gaqTrackEvent('GoogleBouncer','Open','v'+af_GBounce.sourceData,null,true);af_GBounce.open=true;af_utils.tagsDisplay(false);},hide:function(){this.global.style.display='none';this.content.innerHTML='';document.body.style.marginRight='0px';document.body.style.overflow='visible';af_gaqTrackEvent('GoogleBouncer','Close','v'+af_GBounce.sourceData,null,true);af_GBounce.open=false;af_utils.tagsDisplay(true);},resize:function(){var w=af_utils.windowSize();this.container.style.top=Math.max(0,((w.h-this.h-20)/2))+'px';this.container.style.left=Math.max(0,((w.w-this.w-20)/2))+'px';this.background.style.width=w.w+'px';this.background.style.height=this.global.scrollHeight+'px';}}};if(typeof(af_utils)!='undefined'&&af_utils.addEvent){if(typeof(afAdScripts)!='undefined'&&afAdScripts.renderNavAds){af_utils.addEvent(window,'load',function(){afAdScripts.renderNavAds(15132);},false);af_utils.addEvent(window,'load',function(){afAdScripts.renderNavAds(15133);},false);}
if(af_getCookie('cu')==''&&typeof document.getElementsByClassName!='undefined'){var elements=document.getElementsByClassName('connectedUsersOnly');for(var i=0;i<elements.length;i++){var element=elements[i];element.className=element.className.replace('connectedUsersOnly','');if(element.onclick){element.previousOnclick=element.onclick;element.onclick=null;}
af_utils.addEvent(element,'click',af_bind(element,connectedUserOnlyAction),false);}}}
function af_bind(o,m){var args=[];for(var i=2;i<arguments.length;++i){args.push(arguments[i]);}
return function(){var tmp=args.slice(0,args.length);for(var i=0;i<arguments.length;++i){tmp.push(arguments[i]);}
return m.apply(o,tmp);};}
function stopEventPropagation(e){var evt=e?e:window.event;if(typeof evt!='undefined'&&typeof evt.stop!='undefined')evt.stop();if(typeof evt!='undefined'&&typeof evt.preventDefault!='undefined')evt.preventDefault();}
function connectedUserOnlyAction(e){stopEventPropagation(e);if(typeof(SITEID)!='undefined'&&(SITEID==4||SITEID==26)){if(!window.location.origin){window.location.origin=window.location.protocol+"//"+window.location.host;}
destUrl=window.location.origin;window.location=destUrl+"/#login,destUrl="+window.location;}
else{af_utils.popup.show(500,500,'/reloaded/users/login',af_bind(this,function(){setTimeout(af_bind(this,function(){if(this.href){if(typeof af_personalHashValue!='undefined'){var formElements=document.getElementsByName('personalKey');for(var i=0;i<formElements.length;i++){formElements[i].value=af_personalHashValue;}}
if(typeof this.previousOnclick=='undefined'||this.previousOnclick===null||this.previousOnclick()==true){document.location.assign(this.href);}}else{if(this.previousOnclick)this.previousOnclick();}}),100);}));}
return false;}
function af_zoomShow(src,w,h){if(typeof(afvid_stopVideo)!="undefined")afvid_stopVideo();winwidth=window.innerWidth?window.innerWidth:document.body.clientWidth;winheight=window.innerHeight?window.innerHeight:document.body.clientHeight;if(w>winwidth-60||h>winheight-60){cw=(winwidth-60)/w;ch=(winheight-60)/h;c=(cw>ch?ch:cw);w*=c;h*=c;}
popupContent='<img class=af_zoomContent src="'+src+'" width='+w+' height='+h+' border=0 />';af_utils.tagsDisplay(false);af_zoomWindow(popupContent,w,h);}
var af_zoomBg,af_zoomDiv;function af_zoomWindow(popupContent,w,h){if(!af_zoomBg){af_zoomBg=document.createElement("DIV");af_zoomBg.innerHTML='&nbsp;';af_zoomBg.className='af_zoomBg';document.body.insertBefore(af_zoomBg,document.body.firstChild);af_zoomBg.onclick=af_zoomHide;}
if(!af_zoomDiv){af_zoomDiv=document.createElement("DIV");af_zoomDiv.innerHTML='&nbsp;';af_zoomDiv.className='af_zoom';document.body.insertBefore(af_zoomDiv,af_zoomBg);af_zoomDiv.onclick=af_zoomHide;}
af_zoomDiv.innerHTML=popupContent;winwidth=window.innerWidth?window.innerWidth:document.body.clientWidth;winheight=window.innerHeight?window.innerHeight:document.body.clientHeight;document.body.style.margin="0px";var currScrollTop=(document.documentElement&&document.documentElement.scrollTop)||window.pageYOffset||document.body.scrollTop;var currScrollLeft=(document.documentElement&&document.documentElement.scrollLeft)||window.pageXOffset||document.body.scrollLeft;af_zoomBg.style.height=document.body.scrollHeight+"px";af_zoomDiv.style.left=((winwidth-w-40)/2+currScrollLeft)+"px";af_zoomDiv.style.top=((winheight-h-40)/2+currScrollTop)+"px";af_zoomDiv.style.display='';af_zoomBg.style.visibility='visible';}
function af_zoomHide(){if(typeof(afvid_stopVideo)!="undefined")afvid_stopVideo();if(af_zoomBg)af_zoomBg.style.visibility='hidden';af_zoomDiv.style.display='none';af_utils.tagsDisplay(true);}
function af_zoomTagsShowHide(show){af_utils.logError(8,'af_zoomTagsShowHide');af_utils.tagsDisplay(show);}
function af_zoomTagsShowHide2(items,show){af_utils.logError(8,'af_zoomTagsShowHide2');af_utils.toggleVisibility(items,show);}
var afCookiePolicyBar={openDelay:3000,animationDelay:1000,closeDelay:3000,closed:false,init:function(){if(document.cookie.indexOf('af_cookie_policy')>=0){return;}
if(typeof af_translations==='undefined'||typeof af_translations.messageCookieInformation==='undefined'||af_translations.messageCookieInformation===''){return;}
setTimeout(function(){afCookiePolicyBar.render();afCookiePolicyBar.initEventListeners();},afCookiePolicyBar.openDelay);},render:function(){afCookiePolicyBar.obj=document.createElement('div');afCookiePolicyBar.obj.id='af-cookie-policy';afCookiePolicyBar.obj.className='af-cookie-policy';afCookiePolicyBar.obj.innerHTML='<p class="af-cookie-policy-message">'
+af_translations.messageCookieInformation
+'</p>'
+'<a href="#" id="af-cookie-policy-close" class="af-cookie-policy-close"><span>'+af_translations.messageCookieClose+'</span><span class="icon icon-close-btn"></span></a>';if(italianCookiePolicy)afCookiePolicyBar.obj.innerHTML+='<a href="#" id="af-cookie-policy-ok" class="af-cookie-policy-ok af-btn-v2 pink"><span>'+af_translations.messageCookieOk+'</span></a>';document.body.appendChild(afCookiePolicyBar.obj);this.cookieInfoPopup=afCookiePolicyBar.obj;af_addEvent(afCookiePolicyBar.obj,'transitionend',this.remove.bind(this),false);af_addEvent(afCookiePolicyBar.obj,'webkitTransitionEnd',this.remove.bind(this),false);af_addEvent(afCookiePolicyBar.obj,'mozTransitionEnd',this.remove.bind(this),false);af_addEvent(afCookiePolicyBar.obj,'msTransitionEnd',this.remove.bind(this),false);af_addEvent(afCookiePolicyBar.obj,'oTransitionEnd',this.remove.bind(this),false);},initEventListeners:function(){var closeBtn=document.getElementById('af-cookie-policy-close');if(closeBtn){af_addEvent(closeBtn,'click',this.close.bind(this),false);af_addEvent(closeBtn,'touchend',this.close.bind(this),false);}
if(italianCookiePolicy){var okBtn=document.getElementById('af-cookie-policy-ok');if(okBtn){af_addEvent(okBtn,'click',this.close.bind(this),false);af_addEvent(okBtn,'touchend',this.close.bind(this),false);}
af_addEvent(document.body,'click',this.close.bind(this),false);}
if(!italianCookiePolicy)af_addEvent(window,'scroll',this.close.bind(this),false);},close:function(e){af_stopEvent(e);if(afCookiePolicyBar.closed){return false;}
afCookiePolicyBar.closed=true;afCookiePolicyBar.setCookie('af_cookie_policy',1);this.cookieInfoPopup.classList.add('close');return false;},remove:function(){af_remove(afCookiePolicyBar.obj);},setCookie:function(name,value){var d=new Date();d.setTime(d.getTime()+(365*24*60*60*1000));document.cookie=name+'='+encodeURIComponent(value)+'; expires='+d.toUTCString()+'; domain='+'.'+document.domain+'; path=/';}};af_addEvent(window,'load',afCookiePolicyBar.init,false);
(function(){var lastTime=0;var vendors=['ms','moz','webkit','o'];for(var x=0;x<vendors.length&&!window.requestAnimationFrame;++x){window.requestAnimationFrame=window[vendors[x]+'RequestAnimationFrame'];window.cancelAnimationFrame=window[vendors[x]+'CancelAnimationFrame']||window[vendors[x]+'CancelRequestAnimationFrame'];}
if(!window.requestAnimationFrame){window.requestAnimationFrame=function(callback,element){var currTime=new Date().getTime();var timeToCall=Math.max(0,16-(currTime-lastTime));var id=window.setTimeout(function(){callback(currTime+timeToCall);},timeToCall);lastTime=currTime+timeToCall;return id;};}
if(!window.cancelAnimationFrame){window.cancelAnimationFrame=function(id){clearTimeout(id);};}}());var AufHeader=(function(){AufHeader=function(){};AufHeader.prototype={options:{isNavOpen:false},subNav:0,constructor:AufHeader,init:function(opts){var _this=this;this.options.header=document.getElementById('header');this.options.hamburger=document.getElementById('hamburger-menu');this.options.hamburgerDesktop=document.getElementById('hamburger-desktop');this.options.search=document.getElementById('search-open-buton');this.options.userZone=document.getElementById('user-zone');this.options.searchPlaceholder=opts.searchPlaceholder;af_addEvent(this.options.hamburger,'click',this.openMenu.bind(this),false);af_addEvent(this.options.hamburgerDesktop,'click',this.showNav.bind(this),false);af_addEvent(this.options.search,'click',this.searchForm.bind(this),false);af_addEvent(this.options.userZone,'click',this.connect.bind(this),false);PubSub.subscribe('header.pushContent',function(msg,data){_this.pushContent(data.forceClose);});PubSub.subscribe('header.subNav',function(msg,data){_this.subNav=data.level;});if(typeof this.scrollHandler!=='function'){this.scroll={dir:'down'};this.headerCtn=document.getElementsByTagName('header')[0];this.headerOffsetHeight=this.headerCtn.offsetHeight;this.cssTransform=this.detectCSSTransform();this.has3d=this.has3d();if(this.headerCtn){this.contentCtn=document.getElementById('content');this.dfpInterstitial=document.getElementById('madd_top');this.stickyMeganner=document.getElementById('sticky-megabanner');af_addEvent(window,'scroll',this.shrinkHeader.bind(this),false);}}},openMenu:function(e){var icon=this.options.hamburger.getElementsByClassName('icon')[0];if(!this.subNav){icon.classList.toggle('icon-burger-menu');icon.classList.toggle('icon-arrow-left');PubSub.publish('mainNav.open');}else if(this.subNav===2){PubSub.publish('mainNav.subSubMenuClose');this.subNav=1;}else{PubSub.publish('mainNav.subMenuClose');this.subNav=0;}
af_stopEvent(e);},hideHamburgerDesktop:function(){if(typeof this.options.hamburgerDesktop==='object'){this.options.hamburgerDesktop.style.display='none';}},showHamburgerDesktop:function(){if(typeof this.options.hamburgerDesktop==='object'){this.options.hamburgerDesktop.style.display='inline-block';}},hideNav:function(){PubSub.publish('mainNav.hideNav');this.options.isNavOpen=false;},showNav:function(e){PubSub.publish('mainNav.showNav');this.options.isNavOpen=true;this.hideHamburgerDesktop();af_stopEvent(e);},searchForm:function(e){if(!document.getElementById('search-header-form')){var form=document.createElement('form');form.id='search-header-form';form.setAttribute('action','/world/communaute/search/search.asp');var input=document.createElement('input');input.setAttribute('name','kw');input.setAttribute('type','text');input.setAttribute('placeholder',this.options.searchPlaceholder);input.setAttribute('value','');form.appendChild(input);var btn=document.createElement('input');btn.className='af-btn-v2 pink mini';btn.setAttribute('name','s');btn.setAttribute('type','submit');btn.setAttribute('value','Ok');form.appendChild(btn);this.options.search.parentNode.appendChild(form);this.options.searchForm=form;setTimeout(function(){form.classList.add('open');},100);this.options.search.style.display='none';}
af_stopEvent(e)},pushContent:function(forceClose){if(forceClose){this.options.header.classList.remove('push-content');}else{this.options.header.classList.toggle('push-content');}},connect:function(e){var _t=af_getParent(af_getTarget(e),'#user-zone');if(_t.classList.contains('logged')){document.getElementById('dropdown-user').classList.toggle('open');}else{var signIn=document.getElementById('sign-in');var url=window.location.href;if(url.indexOf("destUrl")<0){signIn.setAttribute('href',signIn.getAttribute('href')+'?destUrl='+top.document.location);}else{signIn.setAttribute('href',signIn.getAttribute('href')+'?destUrl='+url.split('destUrl=')[1]);}}},canStickMegabanner:function(){return af_canRefreshAds()&&this.stickyMeganner&&!this.dfpInterstitial;},shrinkHeader:function(){this.setScrollY();var bodyPaddingTop=parseInt(document.body.style.paddingTop,10)||0;var offsetTop;if(this.scroll.y<(bodyPaddingTop+100)||this.scroll.dir==='up'){if(this.scroll.y<(bodyPaddingTop+100)){this.hideNav();this.hideHamburgerDesktop();}else if(!this.options.isNavOpen){this.showHamburgerDesktop();}
offsetTop=0;}else{offsetTop=this.headerOffsetHeight;this.hideNav();}
var styleProp,styleValue;if(this.cssTransform){styleProp=this.cssTransform;if(this.has3d){styleValue='translate3d(0, -'+offsetTop+'px, 0)'}else{styleValue='translate(0, -'+offsetTop+'px)';}}else{styleProp='top';styleValue=(bodyPaddingTop-offsetTop)+'px';}
var that=this;window.requestAnimationFrame(function(){that.headerCtn.style[styleProp]=styleValue;that.headerCtn.style.opacity=1-(offsetTop/that.headerOffsetHeight);if(that.canStickMegabanner()){if(!that.stickyMeganner.classList.contains('fixed')){that.stickyMeganner.classList.add('fixed');if(that.contentCtn){that.contentCtn.style.top=that.stickyMeganner.offsetHeight+'px';}}
that.stickyMeganner.style[styleProp]=styleValue;}});},detectCSSTransform:function(){var prefixes='transform webkitTransform mozTransform oTransform msTransform'.split(' '),el=document.createElement('div'),cssTransform,i=0;while(cssTransform===undefined){cssTransform=document.createElement('div').style[prefixes[i]]!==undefined?prefixes[i]:undefined;i++;}
return cssTransform;},has3d:function(){if(!window.getComputedStyle){return false;}
var el=document.createElement('p'),has3d,transforms={'webkitTransform':'-webkit-transform','OTransform':'-o-transform','msTransform':'-ms-transform','MozTransform':'-moz-transform','transform':'transform'};document.body.insertBefore(el,null);for(var t in transforms){if(el.style[t]!==undefined){el.style[t]='translate3d(1px,1px,1px)';has3d=window.getComputedStyle(el).getPropertyValue(transforms[t]);}}
document.body.removeChild(el);return(has3d!==undefined&&has3d.length>0&&has3d!=='none');},setScrollY:function(e){var windowYOffset=window.pageYOffset||document.documentElement.scrollTop;if(typeof this.scroll.y==='undefined'){this.scroll.y=windowYOffset;}
this.scroll.diffY=this.scroll.y-windowYOffset;if(this.scroll.diffY<0){this.scroll.dir='down';}else if(this.scroll.diffY>0){this.scroll.dir='up';}
this.scroll.y=windowYOffset;}};return AufHeader;})();
if(typeof userId!=='undefined'&&userId){var callApi=false;try{lastMpRefresh=localStorage.getItem('lastPMRefresh');if(lastMpRefresh){diff=new Date()-new Date(lastMpRefresh);callApi=(diff>(1000*30));}else{callApi=true;}}catch(e){}
if(typeof initLocalStorage!=='undefined'&&initLocalStorage){callApi=true;}
if(window.location.href.indexOf('/message/')>-1){callApi=true;}
if(callApi){localStorage.setItem('lastPMRefresh',new Date());af_requestGet('/reloaded/api/user-light/'+userId,'',function(data){var obj=JSON.parse(data);localStorage.setItem('username',obj.userName);localStorage.setItem('avatarUrl',obj.thumbnailURL);localStorage.setItem('nbUnreadPM',obj.nbUnreadPM);localStorage.setItem('nbUnreadFavorites',obj.nbUnreadFavorites);buildconnectedHeader(userId,obj.userName,obj.thumbnailURL,obj.nbUnreadPM,obj.nbUnreadFavorites);});}}
var AufSButtons=(function(){AufSButtons=function(){this.options={socialsBtn:null,type:null};};AufSButtons.prototype={constructor:AufSButtons,init:function init(id,type,infos){this.options.socialsBtn=document.getElementById(id);this.options.infos=infos;var isLocalStorage=typeof(Storage)!=='undefined'?1:0;if(this.options.socialsBtn){this.options.type=type;this.options.retourShare='';this.options.retour='';this.options.af_ShareURL='';if(typeof(infos['extra-info'])!=='undefined'&&infos['extra-info'].position!==''){this.options.uaEvt=infos['extra-info'].position+'ContentClick';}else{this.options.uaEvt='MenuClick';}
if(typeof(infos['share-info'])!=='undefined'&&infos['share-info'].nbShareTotal!==''){this.options.retourShare='<span class="af-nb-share">'+'<span class="af-nb-share-value">'+infos['share-info'].nbShareTotal+'<br /></span>'+'<span>'+infos['share-info'].nbShareLabel+'</span></span>';}
if(typeof this.options.af_ShareURL!=='undefined'){var metas=document.getElementsByTagName('meta');for(var i=0;i<metas.length;i++){if(metas[i].getAttribute('property')==='og:url'){this.options.af_ShareURL=metas[i].getAttribute('content');break;}}
if(typeof this.options.af_ShareURL==='undefined'){this.options.af_ShareURL=document.location.href;}}
if(this.options.af_ShareURL===''){this.options.af_ShareURL=document.location.href;}
this.options.sButtons_referer='';var now=Math.round(Date.now()/1000);var lifeTime=now-(60*30);var afDomain='^http(s?):\/\/:'+window.location.hostname;afDomain=afDomain.replace(/\./g,'\\.');var patt=new RegExp(afDomain);var _referrer=document.referrer;if(!patt.exec(_referrer)){for(var j in infos['social-info']){if(typeof infos['social-info'][j]==='object'){var _patt=infos['social-info'][j].refererDomaine.replace(/\./g,'\\.');var _expg=new RegExp(_patt);var _socialReferrer=_expg.exec(_referrer);if(isLocalStorage&&_socialReferrer){localStorage.setItem('sButtons_referer',_socialReferrer);localStorage.setItem('sButtons_date',now);break;}}}}
if(isLocalStorage){var sButtons_date=localStorage.getItem('sButtons_date');if(sButtons_date>=lifeTime){localStorage.setItem('sButtons_date',now);this.options.sButtons_referer=localStorage.getItem('sButtons_referer');}else{localStorage.removeItem('sButtons_date');localStorage.removeItem('sButtons_referer');}}
this.makeButtons(this.options.infos['social-info']);}
PubSub.subscribe('sButton:update',af_bind(this,this.refreshDatas));},getPopupSize:function(name){var SIZES={facebook:[400,400],'google +':[680,489],pinterest:[830,620],twitter:[520,542]}
if(name&&SIZES[name]){return SIZES[name];}else{return[300,300];}},makeButtons:function(arr){var that=this;this.options.retour=this.options.retourShare;this.options.socialsBtn.innerHTML=this.options.retour;for(var k in arr){var _current=arr[k];if(typeof _current==='object'){var _refererDomaine=_current.refererDomaine;if(this.options.sButtons_referer!==''&&_refererDomaine!==this.options.sButtons_referer){continue;}
var _title='';if(_current.title){_title='&description='+encodeURI(_current.title)+'&text='+encodeURI(_current.title);}
var _ogImage=getMetaImage();if(_ogImage){var paramName=_current.name==='Facebook'?'picture':'media';_ogImage='&'+paramName+'='+_ogImage;}
if(typeof _current.urlComplete!=='undefined'){this.options.af_ShareURL=_current.urlComplete;}
var _name=_current.name;if(this.options.sButtons_referer===_refererDomaine){_name=' <span class="alone">'+label_share+' '+_name+facebookExtra+'</span>';}else{_name=k<1?' <span>'+_name+'</span>':'';}
var a=document.createElement('a');a.href=_current.url+encodeURIComponent(this.options.af_ShareURL)+_title+_ogImage;a.className='af-btn af-btn-'+_current.classCSS;a.target='_blank';if(_current.name==='Pinterest'){a.setAttribute('data-pin-custom',true);a.setAttribute('data-pin-do','none');}
a.setAttribute('data-share-name',_current.name);a.setAttribute('data-track-classname',_current.classCSS);var icon=document.createElement('i');icon.className='icon icon-'+_current.classCSS+_current.extraClass;a.innerHTML=_name;a.insertBefore(icon,a.firstChild);af_addEvent(a,'click',function(e){af_stopEvent(e);var el=af_getParent(af_getTarget(e),'a');var size=that.getPopupSize(el.getAttribute('data-share-name').toLowerCase());af_ua_trackEvent('Share',that.options.uaEvt,el.getAttribute('data-track-classname'),0);window.open(el.href,'Share','width='+size[0]+',height='+size[1]);},false);this.options.socialsBtn.appendChild(a);if(this.options.sButtons_referer==='facebook.com'){if(_current.fbLikeButton&&_current.fbPageURL){var div=document.createElement('div');div.className='fb-like';div.setAttribute('data-href',_current.fbPageURL);div.setAttribute('data-layout','box_count');div.setAttribute('data-action','like');div.setAttribute('data-size','small');div.setAttribute('data-share','false');div.setAttribute('data-show-faces','false');this.options.socialsBtn.appendChild(div);}}
if(!af_isMobile()&&_current.urlFollowUs&&this.canShowFollowUs(this.options.sButtons_referer)){var timer;var followUsSize=this.getFollowUsSize(this.options.sButtons_referer);this.scrollHandler=this.onScroll.bind(this,this.options.sButtons_referer,_current.urlFollowUs,followUsSize[0],followUsSize[1],timer);af_addEvent(window,'scroll',this.scrollHandler,false);}}}},refreshDatas:function(){var obj={};var metas=document.getElementsByTagName('meta');var mLen=metas.length;for(var i=0;i<mLen;i++){var _meta=metas[i].getAttribute('property');if(_meta&&_meta.toLowerCase()==='og:image'){obj['image']=metas[i].getAttribute('content');}else if(_meta&&_meta.toLowerCase()==='og:title'){obj['title']=metas[i].getAttribute('content');}else if(_meta&&_meta.toLowerCase()==='og:description'){obj['description']=metas[i].getAttribute('content');}else if(_meta&&_meta.toLowerCase()==='og:url'){obj['urlComplete']=metas[i].getAttribute('content');}}
for(var j in this.options.infos['social-info']){this.options.infos['social-info'][j].title=obj['title'];this.options.infos['social-info'][j].image=obj['image'];this.options.infos['social-info'][j].urlComplete=obj['urlComplete'];}
this.makeButtons(this.options.infos['social-info']);},getFollowUsSize:function(referer){switch(referer){case'facebook.com':return[290,300];case'pinterest.com':return[290,510];default:return[300,300];}},canShowFollowUs:function(referer){switch(referer){case'facebook.com':return this.canShowFollowUsFacebook();case'pinterest.com':return this.canShowFollowUsPinterest();default:return false;}},canShowFollowUsFacebook:function(){return typeof localStorage!=='undefined'&&localStorage.getItem('af-follow-us-fb')!=='1';},canShowFollowUsPinterest:function(){return typeof localStorage!=='undefined'&&localStorage.getItem('af-follow-us-pin')!=='1';},onScroll:function(referer,url,w,h,timer){if(this.canShowFollowUs(referer)){var socialCtn=document.getElementById('af-socials-btn-story-bottom');clearTimeout(timer);timer=setTimeout(function(){if(af_popup_social&&socialCtn){if(socialCtn.getBoundingClientRect().bottom<=window.innerHeight){af_popup_social.show(url,w,h);}else{af_popup_social.hide();}}},100);}else if(typeof this.scrollHandler==='function'){af_removeEvent(window,'scroll',this.scrollHandler,false);}}};return AufSButtons;})();function getMetaImage(){var metas=document.getElementsByTagName('meta');var len=metas.length;for(var i=0;i<len;i++){var meta=metas[i];var property=meta.getAttribute('property');if(property&&property.toLowerCase()==='og:image'){return meta.getAttribute('content');}}
return'';}
var AufMainNav=(function(){AufMainNav=function(){};AufMainNav.prototype={options:{listWidth:0,currentPosition:0,opsItem:0},tmpEvt:null,currentOpen:null,currentSubOpen:null,navDropdownSectionsCalled:[],navDropdownSectionsDone:[],constructor:AufMainNav,init:function(){var _this=this;this.options.mainDivCtn=document.getElementById('main-nav-container');this.options.mainDiv=document.getElementById('main-nav');this.options.mainDivUl=document.getElementsByClassName('main-menu-items')[0];this.options.mainDivItems=this.options.mainDivUl.getElementsByClassName('item');this.options.mainItemsLink=this.options.mainDivUl.getElementsByClassName('item-link');this.options.mainItemsSubLink=this.options.mainDivUl.getElementsByClassName('sub-item-link');this.options.mainDivItem=this.options.mainDivItems[0];this.options.menuMore=document.getElementById('menu-more');this.options.moreBtnWidth=this.options.menuMore.offsetWidth;this.options.socialFooter=document.getElementsByClassName('more-content-social')[0];this.options.selectedItem=this.options.mainDivUl.getElement
af_addEvent(this.options.menuMore,'click',this.slideMenu.bind(this),false);PubSub.subscribe('mainNav.open',function(msg,data){_this.switchState(false);});PubSub.subscribe('mainNav.addItem',function(msg,data){_this.addMainOpsItem(data);});PubSub.subscribe('mainNav.itemHoverInit',function(msg,data){_this.navDropDownInit();});PubSub.subscribe('mainNav.itemHoverCallback',function(msg,data){_this.itemHoverCallback(data);});PubSub.subscribe('mainNav.subMenuClose',function(){_this.subMenuClose();});PubSub.subscribe('mainNav.subSubMenuClose',function(){_this.subMenuClose();});PubSub.subscribe('mainNav.hideNav',this.hideNav.bind(this));PubSub.subscribe('mainNav.showNav',this.showNav.bind(this));for(var i in this.options.mainItemsLink){if(typeof this.options.mainItemsLink[i]==='object'){var item=this.options.mainItemsLink[i];if(!item.parentNode.classList.contains('no-sub')){af_addEvent(item,'click',this.subMenu.bind(this),false);af_addEvent(item.nextElementSibling,'transitionend',this.transitionFinished.bind(this),false);af_addEvent(item.nextElementSibling,'webkitTransitionEnd',this.transitionFinished.bind(this),false);af_addEvent(item.nextElementSibling,'mozTransitionEnd',this.transitionFinished.bind(this),false);af_addEvent(item.nextElementSibling,'msTransitionEnd',this.transitionFinished.bind(this),false);af_addEvent(item.nextElementSibling,'oTransitionEnd',this.transitionFinished.bind(this),false);}}}
if(this.getScreenWidth()<1024){for(var j in this.options.mainItemsSubLink){if(typeof this.options.mainItemsSubLink[j]==='object'){var subItem=this.options.mainItemsSubLink[j];if(!subItem.parentNode.classList.contains('no-sub')){af_addEvent(subItem,'click',this.subSubMenu.bind(this),false);}}}}
if(typeof appHeaderAds==='object'){appHeaderAds.init();}
this.showOffsetItem();},hideNav:function(){if(typeof this.options.mainDivCtn==='object'){this.options.mainDivCtn.classList.remove('fixed');}},showNav:function(){if(typeof this.options.mainDivCtn==='object'){this.options.mainDivCtn.classList.add('fixed');}},showOffsetItem:function(){var selectedItem=this.options.mainDivUl.getElementsByClassName('selected');if(this.getScreenWidth()>=1024&&selectedItem[0]&&selectedItem[0].offsetLeft>=this.options.menuMore.offsetLeft-this.options.moreBtnWidth){this.options.menuMore.click();}},getScreenWidth:function(){return window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth;},switchState:function(forceClose){if(this.getScreenWidth()<1024){this.options.mainDiv.classList.toggle('open');}else{if(forceClose){PubSub.publish('header.pushContent',{forceClose:forceClose});this.options.mainDiv.parentNode.classList.remove('fixed');}else{this.options.mainDiv.parentNode.classList.toggle('fixed');PubSub.publish('header.pushContent',{forceClose:forceClose});}}},subMenu:function(e){this.options.mainDiv.scrollTop=0;if(!af_isMobile()){return true;}
var _this=this;var _t=af_getTarget(e);if(_t.parentNode&&_t.parentNode.getElementsByClassName('sub-menu').length>0){this.currentOpen=_t.parentNode.getElementsByClassName('sub-menu')[0];}
if(typeof this.currentOpen==='object'){document.getElementsByClassName('main-menu-items')[0].classList.add('sub-menu-is-open');this.currentOpen.classList.add('show');setTimeout(function(){if(!_this.currentOpen.getElementsByClassName('more-content-social').length){_this.currentOpen.appendChild(_this.options.socialFooter);}},0);PubSub.publish('header.subNav',{level:1});af_stopEvent(e);}},subMenuClose:function(){this.options.mainDiv.scrollTop=0;var _this=this;if(this.currentSubOpen){this.tmpEvt=this.transitionSubFinished.bind(this);af_addEvent(this.currentSubOpen.parentNode.parentNode,'transitionend',this.tmpEvt,false);af_addEvent(this.currentSubOpen.parentNode.parentNode,'webkitTransitionEnd',this.tmpEvt,false);af_addEvent(this.currentSubOpen.parentNode.parentNode,'mozTransitionEnd',this.tmpEvt,false);af_addEvent(this.currentSubOpen.parentNode.parentNode,'msTransitionEnd',this.tmpEvt,false);af_addEvent(this.currentSubOpen.parentNode.parentNode,'oTransitionEnd',this.tmpEvt,false);this.currentSubOpen.parentNode.parentNode.classList.remove('hide');this.currentOpen.appendChild(this.options.socialFooter);}else{var el=document.getElementsByClassName('main-menu-items')[0];setTimeout(function(){_this.currentOpen.classList.remove('show');el.parentNode.insertBefore(_this.options.socialFooter,el.nextSibling);},200)
el.classList.remove('sub-menu-is-open');}},slideMenu:function(){var itemsNb=this.options.mainDivUl.children.length;var itemWidth=this.options.mainDivItem.offsetWidth+10;var _newPos=0;var _class;if(this.options.currentPosition===0){_newPos=-Math.abs(itemWidth*(itemsNb-11));this.options.currentPosition=_newPos;}else{this.options.currentPosition=0;this.options.menuMore.getElementsByTagName('span')[0].classList.remove('icon-arrow-left');}
this.options.mainDivItems[0].style.marginLeft=_newPos+'px';this.options.menuMore.getElementsByTagName('span')[0].classList.toggle('opposite');},subSubMenu:function(e){this.options.mainDiv.scrollTop=0;var _this=this;var _t=af_getTarget(e);var _p=af_getParent(_t,'.sub-item-link');this.currentSubOpen=_p.nextElementSibling;this.currentSubOpen.classList.add('open');setTimeout(function(){_this.currentSubOpen.parentNode.parentNode.classList.add('hide');if(!_this.currentSubOpen.getElementsByClassName('more-content-social').length){_this.currentSubOpen.appendChild(_this.options.socialFooter);}},0);PubSub.publish('header.subNav',{level:2});af_stopEvent(e);},addMainOpsItem:function(data){var item=document.createElement('li');item.className='item';item.innerHTML='<a class="item-link item-ops" href="'+data.conf.url+'">'+data.conf.text+'</a>'
+'<div style="position:absolute; width:1px; height: 1px; top:-1000px">'+data.conf.scriptCode+'</div>';var menu=document.getElementsByClassName('main-menu-items')[0];var childs=this.options.mainDivUl.children;if(childs.length>=10){if(this.options.opsItem){this.options.mainDivUl.insertBefore(this.options.mainDivUl.children[10-this.options.opsItem],this.options.mainDivUl.children[11]);}
this.options.mainDivUl.insertBefore(item,this.options.mainDivUl.children[10-this.options.opsItem]);++this.options.opsItem;}else{this.options.mainDivUl.appendChild(item);}
if(window.afAd){afAd.subscribeEvent('ad.clean.navitem',function(){item.parentNode.removeChild(item);});}
this.showOffsetItem();},navDropDownInit:function(){var nbItem=this.options.mainDivItems.length;for(var i=0,l=nbItem;i<l;i++){var link=this.options.mainDivItems[i].firstChild;if(link&&link.getAttribute('data-sid')){af_addEvent(link,'mouseover',this.navDropdown.bind(this),false);af_addEvent(link,'touchend',this.navDropdown.bind(this),false);af_addEvent(link,'click',this.navDropdown.bind(this),false);}}},navDropdown:function(e){if(!window.af_navDdPageID||!af_navDdFormatID){return;}
var item=af_getTarget(e);var sectionId=(item?item.getAttribute('data-sid'):0);if(!sectionId||af_inArray(sectionId,this.navDropdownSectionsCalled)){return;}
sas_target=sas_target.replace(/(;|^)r=.*?r(;|$)/gi,';').replace(/;;/gi,';');sas_target=('r='+sectionId+'r;'+sas_target).replace(/;;/gi,';');this.navDropdownSectionsCalled.push(sectionId);if(window.sas&&sas.call){sas.call('std',{siteId:sas_siteId,pageId:af_navDdPageID,formatId:af_navDdFormatID,target:sas_target},{async:true});}
af_stopEvent(e);return false;},itemHoverCallback:function(data){var sectionId=data.target.match(/(;|^)r=.*?r(;|$)/gi);sectionId=(sectionId?sectionId[0].replace(/[;]?r=/gi,'').replace(/r[;]?$/gi,''):0);if(af_inArray(sectionId,this.navDropdownSectionsDone)){return;}
var items=document.getElementById('navSection'+sectionId).getElementsByClassName('sub-item-link');for(var i=0,l=items.length;i<l;i++){var item=items[i];if(item.href.indexOf('forum')>=0||item.href.indexOf('album')>=0||i===l-1){var li=document.createElement('li');li.classList.add('sub-item');li.innerHTML='<a href="'+data.url+'" class="sub-item-link" '+(data.targetBlank?'target="_blank"':'')+'><span>'+data.title+'</span></a>';item.parentNode.parentNode.insertBefore(li,item.parentNode);this.navDropdownSectionsDone.push(sectionId);return;}}},transitionFinished:function(e){var _t=af_getTarget(e);if(!_t.classList.contains('open')){_t.classList.remove('show');}},transitionSubFinished:function(e){af_removeEvent(this.currentSubOpen.parentNode.parentNode,'transitionend',this.tmpEvt,false);af_removeEvent(this.currentSubOpen.parentNode.parentNode,'webkitTransitionEnd',this.tmpEvt,false);af_removeEvent(this.currentSubOpen.parentNode.parentNode,'mozTransitionEnd',this.tmpEvt,false);af_removeEvent(this.currentSubOpen.parentNode.parentNode,'msTransitionEnd',this.tmpEvt,false);af_removeEvent(this.currentSubOpen.parentNode.parentNode,'oTransitionEnd',this.tmpEvt,false);this.currentSubOpen.classList.remove('open');this.currentSubOpen=null;}};return AufMainNav;})();var appAufMainNav=new AufMainNav();jquery$(function(){appAufMainNav.init();});
var AufHeaderSubNav=(function(){AufHeaderSubNav=function(){};AufHeaderSubNav.prototype={options:{ul:null,nav:null,noOverflow:null,width:null,offsetWidth:null,wrapper:null,position:0},constructor:AufHeaderSubNav,init:function init(){var _w=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth;this.options.nav=document.getElementById('sub');if(_w<1024||!this.options.nav){return;}
this.options.ul=this.options.nav.getElementsByTagName('ul')[0];this.options.wrapper=this.options.nav.getElementsByClassName('nav-wrapper')[0];this.options.noOverflow=this.options.wrapper.getElementsByClassName('no-overflow')[0];this.options.width=this.options.ul.scrollWidth;this.options.offsetWidth=this.options.noOverflow.offsetWidth;if(this.options.width>this.options.offsetWidth){this.options.more=document.getElementById('sub-more');this.options.more.classList.add('open');af_addEvent(this.options.more,'click',this.slideMenu.bind(this),false);af_addEvent(this.options.more,'touchend',this.slideMenu.bind(this),false);}},slideMenu:function slideMenu(e){var _t=af_getTarget(e);_t.classList.toggle('opposite');if(this.options.position){this.options.position=0;this.options.ul.style.marginLeft='0';}else{this.options.position=1;var slide=this.options.width-this.options.offsetWidth;this.options.ul.style.marginLeft='-'+slide+'px';}}};return AufHeaderSubNav;})();
var appHeaderSubNav=new AufHeaderSubNav();jquery$(function(){appHeaderSubNav.init();});
